# WanOS mosquitto info & conf-file
# v0.03 - 160317
# v0.04 - 260623
# /etc/mosquitto/conf.d/mosquitto-st.conf

#### INSTALL
# (don’t install Mosquitto directly from the standard Wheezy or Jessie repositories (with apt-get install), otherwise it will be installed BUT you will miss the utility mosquitto_passwd that you need to setup the authentication with login and password)
# http://www.mymakerprojects.com/index.php/setup-mosquitto-mqtt-server-on-the-raspberry-pi/
# http://mosquitto.org/2013/01/mosquitto-debian-repository/
# http://jpmens.net/2013/09/01/installing-mosquitto-on-a-raspberry-pi/

#### CONFIG
# http://mosquitto.org/man/mosquitto-conf-5.html
#using client prefixes results in unstable broker :-(
#clientid_prefixes st00011508271926

allow_anonymous false
password_file /etc/mosquitto/conf.d/st.pwd

# Standard TCP Listener for Python Backend
listener 1883
allow_anonymous true

# WebSocket Listener for Vue.js Frontend
listener 9001
protocol websockets