[global]
    workgroup = WORKGROUP
    server string = WanOS Storage
    server role = standalone server
    security = user

    # Logging
    log file = /var/log/samba/log.%m
    max log size = 1000
    logging = file
    panic action = /usr/share/samba/panic-action %d

	# Disable printer subsystem (improves performance and limits noise)
    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes

    # Guest handling
    map to guest = bad user

[wanos_share]
    comment = WanOS Application Share
    path = /home/wannes/wanos
    valid users = wannes
    browseable = yes
    read only = no
    guest ok = no

    # Permissions: Ensures files and folders are immediately executable (rwxrwxr-x)
    create mask = 0775
    force create mode = 0775
    directory mask = 0775
    force directory mode = 0775