# --- file: integrations/zwave.py ---
import json
import asyncio
from typing import Any, List
from core.models import Event, EventType, SystemState
from core.state_manager import StateManager
from core.logger import WanosComponent


class ZWaveJSUIBridge(WanosComponent):
    def __init__(self, state_manager: StateManager, mqtt_client: Any) -> None:
        super().__init__(state_manager)
        self.mqtt_client = mqtt_client
        self.name_to_idx: dict[str, int] = {}
        self.idx_to_name: dict[int, str] = {}
        self._last_known_states: dict[int, str] = {}
        self._integration_enabled: bool = False
        self.is_physically_connected: bool = False

    async def start(self) -> None:
        # Build bidirectional lookup maps from config.yaml dashboard definitions
        for idx, name in self.state_manager._config.dashboard.items():
            safe_name = name.replace(" ", "_")  # Match Z-Wave JS UI MQTT safe strings
            self.name_to_idx[safe_name] = idx
            self.idx_to_name[idx] = safe_name

        # 1. Listen for INBOUND state changes from the Z-Wave mesh
        await self.mqtt_client.subscribe("zwave/+/+/endpoint_0/currentValue", self._parse_inbound)

        # CODE TO REPLACE IT WITH
        # ⚡ PHYSICAL HARDWARE LWT (LAST WILL & TESTAMENT) SUBSCRIPTION ⚡
        # Listens to Z-Wave JS UI broker status (Alive / Offline)
        await self.mqtt_client.subscribe("zwave/_CLIENTS/+/status", self._parse_hardware_status)

        # 2. Listen for OUTBOUND commands generated by WanOS automations or UI
        self.state_manager.register_listener(self._on_state_changed)

        await self.logger.success(f"[Z-Wave] Z-Wave JS UI Bridge initialized. Mapped {len(self.name_to_idx)} nodes.")

    async def _parse_hardware_status(self, topic: str, payload: str) -> None:
        """
        Parses the LWT payload from Z-Wave JS UI to update self.is_physically_connected.
        Standard Z-Wave JS UI payload: {"value": true, "status": "Alive"} or {"value": false, "status": "Offline"}
        """
        try:
            data = json.loads(payload)
            # We check both value and status for robust compatibility with different Z-Wave JS versions
            is_alive = data.get("value", False) is True or data.get("status") == "Alive"

            if is_alive and not self.is_physically_connected:
                self.is_physically_connected = True
                await self.logger.success("[Z-Wave] Z-Wave JS Engine reported ALIVE.")
            elif not is_alive and self.is_physically_connected:
                self.is_physically_connected = False
                await self.logger.error("🔴 [Z-Wave] Z-Wave JS Engine reported OFFLINE (LWT).")
        except Exception as e:
            await self.logger.error(f"[Z-Wave] Failed to parse hardware LWT status: {e}")

    async def stop(self) -> None:
        await self.logger.warning("[Z-Wave] Z-Wave Bridge stopped.")

    async def _parse_inbound(self, topic: str, payload: str) -> None:
        """Parses physical sensor updates coming from the ZBT-2"""
        if not self._integration_enabled:
            return

        try:
            data: dict[str, Any] = json.loads(payload)
            parts = topic.split('/')

            node_name = parts[1]
            command_class = parts[2]

            target_idx = self.name_to_idx.get(node_name)
            if not target_idx:
                return

            raw_val = data.get("value")

            # Route Binary Switches / Plugs
            if command_class in ["switch_binary", "targetValue"]:
                state_str = "ON" if raw_val in [True, 1, "ON", "true"] else "OFF"

                # Deduplication cache
                if self._last_known_states.get(target_idx) == state_str:
                    return
                self._last_known_states[target_idx] = state_str

                self.state_manager.dispatch(Event(
                    type=EventType.HUB_STATE_CHANGED,
                    payload={
                        "idx": target_idx,
                        "state": state_str,
                        "name": node_name,
                        "device_type": "switch",
                        "origin": "zwave",
                        "is_initialization": False
                    }
                ))

            # Route Power Meters (Electric_W)
            elif command_class == "meter" and "Electric_W" in topic:
                self.state_manager.dispatch(Event(
                    type=EventType.POWER_UPDATED,
                    payload={"idx": target_idx, "value": float(raw_val), "device_type": "power", "origin": "zwave",
                             "name": node_name}
                ))

        except Exception as e:
            await self.logger.error(f"[Z-Wave] Parser error on topic {topic}: {e}")

    async def _on_state_changed(self, state: SystemState, events: List[Event] = None) -> None:
        """Listens to WanOS events and pushes OUTBOUND commands to the ZBT-2"""
        current_enabled = state.system.zwave_integration_enabled
        if current_enabled and not self._integration_enabled:
            self._integration_enabled = True
            await self.logger.success("[Z-Wave] Integration ENABLED via UI.")
        elif not current_enabled and self._integration_enabled:
            self._integration_enabled = False
            await self.logger.info("[Z-Wave] Integration DISABLED via UI.")

        if not self._integration_enabled or not events or not getattr(self.mqtt_client, 'is_connected', False):
            return

        for event in events:
            if event.type != EventType.HUB_STATE_CHANGED:
                continue

            payload = event.payload or {}
            idx = payload.get("idx")
            new_state = payload.get("state")
            origin = payload.get("origin")
            is_force = payload.get("force", False)

            # Prevent infinite loops: Don't echo commands back to Z-Wave if Z-Wave sent them
            if origin == "zwave" and not is_force:
                continue

            node_name = self.idx_to_name.get(idx)
            if not node_name:
                continue

            # Update cache to prevent bounce-back
            self._last_known_states[idx] = new_state

            # Format the target topic for Z-Wave JS UI
            # Z-Wave JS UI listens on ".../targetValue/set"
            target_topic = f"zwave/{node_name}/switch_binary/endpoint_0/targetValue/set"

            # Z-Wave JS UI expects a boolean payload for binary switches
            zwave_payload = {"value": True if new_state == "ON" else False}

            await self.mqtt_client.publish(target_topic, zwave_payload)

            if is_force:
                await self.logger.warning(f"⚡ [FORCED] Z-Wave Command Sent: {node_name} -> {new_state}")
            else:
                await self.logger.info(f"[Z-Wave] Command Sent: {node_name} -> {new_state}")