mqtt:
  broker_host: "localhost"
  port: 1883
  username: "st"           # password in .env

sauna:
  default_setpoint: 80     # Default temperature setpoint
  max_temp: 95             # maximum setpoint that can be set in the UI
  kp: 3.0                  # PID P
  ki: 0.01                 # PID I
  kd: 0.0                  # PID D
  default_timer: 180       # Default sauna duration in minutes
  vent_delay_mins: 1       # Cooldown wait time before starting the extraction fan - will be 10 min
  vent_run_mins: 160       # Duration the extraction fan runs