# --- file: config_lab.yaml ---
# These values are injected on boot.
# The simulator dynamically parses integer keys as IDXs!
boot_seed:
  # --- Metadata ---
  # outside_tick: Artificial time counter used by the Lab Mode simulator to generate a continuous day/night weather sine wave.
  # Changing this acts as a "time travel" dial to boot the simulation in a different phase of the day/night curve.
  outside_tick: 0

  # Sauna Environment
  20001: # sauna_high
    temp: 21.0
    hum: 45.0
  20002: # sauna_low
    temp: 20.0
    hum: 48.0
  10001: # door_sauna
    is_open: true

  # Bathroom 1e
  20004: # bathroom1
    temp: 22.5
    hum: 45.0

  # Cinema
  20003: # cinema
    temp: 21.5
    hum: 50.0

  # Outside (Baselines for the sine wave simulator)
  30001: # outside
    temp: 15.0
    hum: 60.0