# --- file: main.py ---

# WanOS - Smart Home OS & Sauna Controller
# Copyright (C) 2026 Johan Wannes Hofmans (https://github.com/gitwannes)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

import asyncio
import json
import os
import signal
import jwt
import yaml
from contextlib import asynccontextmanager
from typing import Union, Any, AsyncGenerator, Optional
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse, RedirectResponse, JSONResponse, Response
from pydantic import BaseModel
from fastapi.staticfiles import StaticFiles
from loguru import logger
from datetime import datetime, timedelta, timezone

# WanOS specific
from core.models import Event, EventType
from core.mqtt_transport import MqttClientManager
from core.mqtt_publisher import MqttPublisher
from core.state_manager import StateManager
from core.config import load_config, AppConfig
from core.automations_store import (
    append_automation,
    delete_automation,
    read_automations,
    update_automation,
)
from core.automations_api_models import (
    BranchedAutomationRuleRequest,
    FlatAutomationRuleRequest,
    AutomationsRuleIdRequest,
)
from core.logger import setup_wanos_logging, WanosLogger
from hardware.simulator import lab_mode_thermodynamics_loop
from integrations.open_weather import weather_polling_loop
from integrations.zwave import ZWaveJSUIBridge

# Physical Hardware Imports
from hardware.inputs import HardwareInputs
from hardware.sensors import HardwareSensors
from hardware.actuators import HardwareActuators

# Create a global shutdown event kill switch
shutdown_event = asyncio.Event()

# 0. Configure Centralized File Logger
logger.remove()  # 🛑 Silences the default console output entirely
# 0. Initialize WanOS custom Logging
setup_wanos_logging()

# 1. Load and validate the configuration from YAML and .env
config: AppConfig = load_config()

# 2. Inject the config safely into the Local MQTT Transport (local Mosquitto broker)
mqtt_manager: MqttClientManager = MqttClientManager(
    broker_host=config.wanos.mqtt.broker_host,
    port=config.wanos.mqtt.port,
    username=config.wanos.mqtt.username,
    password=config.wanos.mqtt.password
)

# 3. Initialize the Logger and State Manager
wanos_logger: WanosLogger = WanosLogger(mqtt_client=mqtt_manager)
state_manager: StateManager = StateManager(mqtt_client=mqtt_manager, logger=wanos_logger)

# 🚀 The absolute first log entry, pulling the dynamic version string generated by the StateManager
logger.info(f"🚀 WanOS booting - {state_manager._state.system.version_full}...")

# 4. Initialize the domain-scoped MQTT Publisher
# ARCHITECTURE NOTE: This is the "WanOS Correspondent". It knows which domain maps to
# which topic, at which cadence. It receives post-drain snapshots from StateManager
# together with the set of changed domains, and routes each to the correct topic.
# The Postman (mqtt_manager) delivers the packets; this layer decides what to write.
mqtt_publisher: MqttPublisher = MqttPublisher(mqtt_client=mqtt_manager)

# 5. Bind the Z-Wave JS UI Bridge
zwave_bridge = ZWaveJSUIBridge(
    state_manager=state_manager,
    mqtt_client=mqtt_manager  # Uses the primary local WanOS broker
)
state_manager.zwave_bridge = zwave_bridge

# 6. Bind the Native RFXCOM Bridge (Dual-Use Architecture)
# Conditionally loaded to prevent crashes if the config block is omitted.
native_rfx_bridge = None
if getattr(config, "rfxcom", None) and getattr(config.rfxcom, "serial_port", None):
    try:
        from integrations.rfxcom import NativeRFXCOMBridge

        native_rfx_bridge = NativeRFXCOMBridge(
            state_manager=state_manager,
            serial_port=config.rfxcom.serial_port
        )
        # Inject into state_manager for UI telemetry tracking
        state_manager.rfxcom_bridge = native_rfx_bridge
    except Exception as e:
        logger.exception(f"CRITICAL: Crash loading NativeRFXCOMBridge: {e}")

# 7. Bind the Local Hue Bridge (API v2)
hue_bridge = None
logger.debug("DIAGNOSTIC: Checking if Hue config exists...")
if getattr(config, "hue", None) and getattr(config.hue, "bridge_ip", None):
    logger.debug(f"DIAGNOSTIC: Hue config found. IP: {config.hue.bridge_ip}. Attempting to import HueLocalBridge...")
    try:
        from integrations.hue import HueLocalBridge
        logger.debug("DIAGNOSTIC: HueLocalBridge imported successfully. Instantiating...")
        hue_bridge = HueLocalBridge(
            state_manager=state_manager,
            config=config
        )
        logger.debug("DIAGNOSTIC: HueLocalBridge instantiated successfully.")
        # Inject into state_manager for UI telemetry tracking
        state_manager.hue_bridge = hue_bridge
    except Exception as e:
        logger.debug(f"DIAGNOSTIC CRITICAL CRASH during Hue init: {e}")
        # import traceback
        # traceback.print_exc()  # Force raw Python stack trace to console
        logger.exception(f"CRITICAL: Crash loading HueLocalBridge: {e}")
else:
    logger.debug("DIAGNOSTIC: Hue config NOT found or missing bridge_ip.")

# 8. Bind the Epson Projector Bridge
epson_bridge = None
if getattr(config, "epson", None) and getattr(config.epson, "ip_address", None):
    try:
        from integrations.epson import EpsonProjector
        epson_bridge = EpsonProjector(host=config.epson.ip_address)
        state_manager.epson_bridge = epson_bridge
        logger.info(f"Epson Projector Bridge initialized at {config.epson.ip_address}")
    except Exception as e:
        logger.exception(f"CRITICAL: Crash loading EpsonProjector: {e}")

# 9. Bind the Physical Hardware Layer
hw_inputs = HardwareInputs(state_manager=state_manager)
hw_sensors = HardwareSensors(state_manager=state_manager)
hw_actuators = HardwareActuators(state_manager=state_manager)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
    """Manages startup and shutdown sequences safely without silent deadlocks."""

    logger.info("Initializing pre-boot sequence...")

    # Intercept the exact CTRL-C signal to instantly drop the SSE stream
    loop = asyncio.get_running_loop()
    try:
        for sig in (signal.SIGINT, signal.SIGTERM):
            original_handler = signal.getsignal(sig)

            def make_handler(orig=original_handler):
                def custom_handler(signum, frame):
                    def _mark():
                        state_manager._shutting_down = True
                        shutdown_event.set()
                    loop.call_soon_threadsafe(_mark)
                    if callable(orig):
                        orig(signum, frame)

                return custom_handler

            signal.signal(sig, make_handler())
    except Exception:
        pass  # Windows compatibility failsafe

    try:
        # 1. Start Network Transports
        logger.info("Connecting to local Mosquitto MQTT Broker...")
        await mqtt_manager.start()

        # 2. Initialize the state engine and wire up the publisher
        await state_manager.start()

        state_manager.mqtt_publisher = mqtt_publisher
        mqtt_publisher.start()

        # Start external bridges
        logger.debug("DIAGNOSTIC: Awaiting zwave_bridge.start()...")
        await zwave_bridge.start()
        logger.debug("DIAGNOSTIC: zwave_bridge.start() completed successfully.")
        if native_rfx_bridge:
            logger.debug("DIAGNOSTIC: Awaiting native_rfx_bridge.start()...")
            try:
                await native_rfx_bridge.start()
                logger.debug("DIAGNOSTIC: native_rfx_bridge.start() completed successfully.")
            except Exception as e:
                logger.debug(f"DIAGNOSTIC CRASH during await native_rfx_bridge.start(): {e}")
                import traceback
                traceback.print_exc()
        if hue_bridge:
            logger.debug("DIAGNOSTIC: Awaiting hue_bridge.start()...")
            try:
                await hue_bridge.start()
                logger.debug("DIAGNOSTIC: hue_bridge.start() completed successfully.")
            except Exception as e:
                logger.debug(f"DIAGNOSTIC CRASH during await hue_bridge.start(): {e}")
                import traceback
                traceback.print_exc()

        # Start Physical Hardware Layer
        logger.info("Initializing Raspberry Pi Hardware Layer...")
        await hw_inputs.start()
        await hw_sensors.start()
        await hw_actuators.start()

        # 3. Seed initial state parameters
        state_manager.dispatch(Event(type=EventType.SYSTEM_READY))
        logger.info("Core systems online. Base state ready.")

        # AUTOSTART SEQUENCE
        # Evaluates .env configuration. Spawns a non-blocking background task to wait
        # 5 seconds for local network sockets to stabilize, then fires the Master Start Sequence.
        if os.getenv("WANOS_AUTOSTART", "False").lower() == "true":
            async def delayed_autostart():
                await asyncio.sleep(5.0)
                logger.info("🚀 Executing automated Master Start Sequence (WANOS_AUTOSTART=True)...")
                # Phase 1: Arm the Brain
                state_manager.dispatch(Event(type=EventType.AUTOMATIONS_TOGGLED, payload={"enabled": True}))
                # Phase 2: Power the Actuators
                state_manager.dispatch(Event(type=EventType.HUE_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.EPSON_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.RFXCOM_TOGGLED, payload={"enabled": True}))
                # Phase 3: Enable Sonos & Onkyo
                state_manager.dispatch(Event(type=EventType.SONOS_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.ONKYO_TOGGLED, payload={"enabled": True}))
                # Phase 4: Enable Z-Wave (may defer silently until MQTT data plane is alive;
                # telemetry auto-recovery arms it when ready — no false "frozen" reject alert).
                state_manager.dispatch(Event(type=EventType.ZWAVE_TOGGLED, payload={"enabled": True}))
                # Phase 5: The OWM Cloud
                state_manager.dispatch(Event(type=EventType.OWM_TOGGLED, payload={"enabled": True}))
                # Phase 6: Arm Hardware Inputs
                state_manager.dispatch(Event(type=EventType.GPIO_INPUT_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.SHT11_TOGGLED, payload={"enabled": True}))
                # Phase 7: Wait for stabilization (Give SHT11 loop time to parse real-world temps)
                await asyncio.sleep(2.0)
                # Phase 8: Synchronization Sweep (Outputs remain safely disarmed until UI manual intervention)
                state_manager.dispatch(Event(type=EventType.SYSTEM_SWEEP_REQUESTED, payload={}))

            asyncio.create_task(delayed_autostart())

        # 4. Start the thermodynamics engine in the background
        logger.info("Simulation engine booting...")
        physics_task = asyncio.create_task(lab_mode_thermodynamics_loop(state_manager))
        logger.info("Simulation engine initialized.")

        # 5. Start the OWM polling loop
        logger.info("[OWM] loop starting...")
        weather_task = asyncio.create_task(weather_polling_loop(state_manager))
        logger.info("[OWM] loop initialized.")

    except Exception as startup_err:
        logger.error(f"Core initialization collapsed: {startup_err}")
        os._exit(1)

    logger.success("Boot sequence complete. HTTP/SSE Web Interface online.")
    yield

    # Shutdown sequence
    logger.warning("Tearing down background engines...")
    state_manager._shutting_down = True
    shutdown_event.set()
    physics_task.cancel()
    weather_task.cancel()
    mqtt_publisher.stop()

    # Stop the physical hardware layer gracefully
    await hw_inputs.stop()
    await hw_sensors.stop()
    await hw_actuators.stop()

    if native_rfx_bridge:
        await native_rfx_bridge.stop()
    if hue_bridge:
        await hue_bridge.stop()
    await zwave_bridge.stop()

    await state_manager.stop()
    await mqtt_manager.stop()
    logger.success("Clean teardown complete. Goodbye.")

# Initialize FastAPI
app: FastAPI = FastAPI(lifespan=lifespan, title="WanOS Backend API")


# Server-Side strike tracker for brute-force protection
failed_attempts: dict[str, dict] = {}


@app.middleware("http")
async def rbac_security_middleware(request: Request, call_next):
    """Universal Pre-Flight Interceptor enforcing RBAC via Tab-Isolated JWTs."""
    path = request.url.path

    # 1. Allow open access to all static assets AND HTML pages initially.
    # The frontend JS will enforce redirection if its API calls fail.
    if path.endswith((".js", ".css", ".png", ".ico", ".svg", ".html")) and not path.startswith("/api/"):
        return await call_next(request)

    # 2. Redirect root directly to login, preserving query params (magic links)
    if path == "/":
        query_string = request.url.query
        target_url = f"/login.html?{query_string}" if query_string else "/login.html"
        return RedirectResponse(url=target_url, status_code=302)

    # 3. Allow public access to the login endpoint itself
    if path == "/api/auth/login":
        return await call_next(request)

    # 4. EXTRACT TOKEN (From Header for standard API calls, or Query string for SSE stream)
    token = None
    auth_header = request.headers.get("Authorization")
    if auth_header and auth_header.startswith("Bearer "):
        token = auth_header.split(" ")[1]
    elif request.query_params.get("jwt"):
        token = request.query_params.get("jwt")

    # 5. Verify the Token
    role = None
    if token:
        try:
            payload = jwt.decode(token, config.auth.secret_key, algorithms=["HS256"])
            role = payload.get("role")
        except Exception:
            pass

    # 6. Block unauthenticated access to the backend APIs
    if not role and path.startswith("/api/"):
        return JSONResponse(status_code=401, content={"detail": "Unauthorized. Session expired."})

    # Store role in request state so downstream endpoints can verify admin privileges
    request.state.role = role
    return await call_next(request)


class LoginRequest(BaseModel):
    pin: Optional[str] = None
    token: Optional[str] = None


@app.post("/api/auth/login")
async def login(req: LoginRequest, request: Request):
    # Use X-Forwarded-For if available to get the true client IP
    forwarded_for = request.headers.get("x-forwarded-for")
    if forwarded_for:
        client_ip = forwarded_for.split(",")[0].strip()
    else:
        client_ip = request.client.host

    now = datetime.now(timezone.utc)

    # Lazy cleanup: remove expired bans to prevent memory leaks
    expired_ips = [ip for ip, record in failed_attempts.items() if record["lockout_until"] and record["lockout_until"] < now]
    for ip in expired_ips:
        del failed_attempts[ip]

    # 1. Check IP Ban Status
    strike_record = failed_attempts.get(client_ip, {"strikes": 0, "lockout_until": None})
    if strike_record["lockout_until"] and now < strike_record["lockout_until"]:
        mins_left = int((strike_record["lockout_until"] - now).total_seconds() / 60) + 1
        return JSONResponse(status_code=429, content={"error": f"Too many attempts. Locked out for {mins_left} minutes."})

    # 2. Evaluate Credentials
    role = None
    if req.token:
        if req.token == config.auth.user_token: role = "user"
        elif req.token == config.auth.kiosk_token: role = "kiosk"
    elif req.pin:
        if req.pin == config.auth.admin_pin: role = "admin"
        elif req.pin == config.auth.user_pin or req.pin == config.auth.shared_pin: role = "user"

    # 3. Handle Failure
    if not role:
        strike_record["strikes"] += 1
        if strike_record["strikes"] >= 3:
            strike_record["lockout_until"] = now + timedelta(minutes=config.auth.ban_timeout_mins)
            strike_record["strikes"] = 0
            failed_attempts[client_ip] = strike_record
            return JSONResponse(status_code=429, content={"error": f"Too many attempts. Locked out for {config.auth.ban_timeout_mins} minutes."})

        failed_attempts[client_ip] = strike_record
        return JSONResponse(status_code=401, content={"error": "Invalid PIN."})

    # 4. Success -> Clear strikes & Issue JWT in Payload
    if client_ip in failed_attempts:
        del failed_attempts[client_ip]

    expiration = now + timedelta(days=config.auth.cookie_expiry_days)
    jwt_payload = {"role": role, "exp": expiration}
    token = jwt.encode(jwt_payload, config.auth.secret_key, algorithm="HS256")

    target_url = "/deviceexplorer.html" if role in ["admin", "user"] else "/kiosk.html"

    # Send the token directly in the JSON response body
    return JSONResponse(content={"status": "Success", "role": role, "redirect": target_url, "token": token})


@app.post("/api/auth/logout")
async def logout():
    # Cookie deletion removed. The frontend is now responsible for wiping its local tab memory.
    return JSONResponse(content={"status": "Logged out"})


class GenericEventRequest(BaseModel):
    type: Union[EventType, str]
    payload: dict[str, Any] = {}


class ZwaveConfigRequest(BaseModel):
    yaml_content: str


@app.post("/api/config/zwave")
async def update_zwave_config(request: ZwaveConfigRequest, req: Request):
    """Directly injects the YAML payload from the UI into the local server file."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    # Validate YAML content before saving
    try:
        yaml.safe_load(request.yaml_content)
    except yaml.YAMLError as e:
        logger.error(f"Invalid YAML payload received: {e}")
        return JSONResponse(status_code=400, content={"error": "Invalid YAML format."})

    try:
        file_path = os.path.join(os.path.dirname(__file__), "config_zwave.auto.yaml")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(request.yaml_content)
        return {"status": "Success", "message": "Z-Wave configuration written to disk."}
    except Exception as e:
        logger.error(f"Failed to write Z-Wave config from UI: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to save configuration file on server."})


@app.get("/api/automations")
async def list_automations(req: Request) -> dict[str, Any]:
    """Admin: list stored automations in Y1 branched shape (for on/off rules) + flat SYNC rules."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    rules = read_automations()
    return {"automations": rules}


@app.post("/api/automations")
async def create_automation(rule: dict[str, Any], req: Request) -> dict[str, Any]:
    """Admin: create a new automation rule in automations.auto.yaml (surgical append; comments kept)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    # Detect Y1 branched vs flat by presence of on/off keys.
    try:
        if ("on" in rule) or ("off" in rule):
            parsed = BranchedAutomationRuleRequest.model_validate(rule)
        else:
            parsed = FlatAutomationRuleRequest.model_validate(rule)
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Invalid automation payload: {e}"})

    # Backend-only rule identity (B1): if missing, generate it here.
    import uuid
    new_rule = parsed.model_dump(exclude_none=True, by_alias=True)
    if not new_rule.get("id"):
        new_rule["id"] = str(uuid.uuid4())

    current = read_automations()
    if any(isinstance(r, dict) and r.get("id") == new_rule["id"] for r in current if r.get("id") is not None):
        return JSONResponse(status_code=409, content={"error": "Duplicate automation id."})

    # Persist exactly the stored shape (branched if on/off, otherwise flat).
    # Surgical append keeps comments on existing rules + other top-level keys.
    append_automation(new_rule)

    # Hot reload logic config + engine cache
    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={}))
    return {"status": "Success", "automation": new_rule}


@app.put("/api/automations")
async def update_automation_api(rule: dict[str, Any], req: Request) -> dict[str, Any]:
    """Admin: replace an automation rule (identified by rule.id) inside automations.auto.yaml."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    try:
        if ("on" in rule) or ("off" in rule):
            parsed = BranchedAutomationRuleRequest.model_validate(rule)
        else:
            parsed = FlatAutomationRuleRequest.model_validate(rule)
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Invalid automation payload: {e}"})

    if not getattr(parsed, "id", None):
        return JSONResponse(status_code=400, content={"error": "PUT requires a stable automation rule `id`."})

    dumped = parsed.model_dump(exclude_none=True, by_alias=True)
    if not update_automation(parsed.id, dumped):
        return JSONResponse(status_code=404, content={"error": f"Automation id '{parsed.id}' not found."})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={}))
    return {"status": "Success", "automation": dumped}


@app.delete("/api/automations")
async def delete_automation_api(req_body: AutomationsRuleIdRequest, req: Request) -> dict[str, Any]:
    """Admin: delete an automation rule by id from automations.auto.yaml."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    if not delete_automation(req_body.id):
        return JSONResponse(status_code=404, content={"error": f"Automation id '{req_body.id}' not found."})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={}))
    return {"status": "Success"}


@app.get("/api/state")
async def get_state() -> dict[str, Any]:
    return state_manager.get_state_snapshot().model_dump()


@app.get("/api/debug/entity-registry-check")
async def debug_entity_registry_check(req: Request) -> dict[str, Any]:
    """Admin Debug: entity_id / automation consistency checks (keep after cutover)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    from core.entity_registry_check import run_entity_cutover_checks

    report = run_entity_cutover_checks(
        device_metadata=state_manager.get_state_snapshot().device_metadata,
    )
    return report


@app.get("/api/admin/entity-id-list")
async def admin_entity_id_list(req: Request):
    """Admin: download live entity_id authoring list (core.entity_id_list)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    from core.entity_id_list import generate_entity_id_list_text

    try:
        text = generate_entity_id_list_text()
    except FileNotFoundError as e:
        return JSONResponse(status_code=404, content={"error": str(e)})
    except Exception as e:
        logger.error(f"Failed to generate entity_id list: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to generate entity_id list."})

    return Response(
        content=text,
        media_type="text/plain; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="entity_id-list.txt"'},
    )


def _require_history_reader(req: Request):
    """Device/session history is available to admin and user roles."""
    if req.state.role not in ("admin", "user"):
        return JSONResponse(status_code=403, content={"error": "Forbidden: Login required."})
    return None


@app.get("/api/history/sensors")
async def history_sensors(req: Request):
    denied = _require_history_reader(req)
    if denied:
        return denied
    return {"sensors": state_manager.sensor_history.list_sensors()}


@app.get("/api/history/actuators")
async def history_actuators(req: Request):
    denied = _require_history_reader(req)
    if denied:
        return denied
    return {"actuators": state_manager.history_manager.list_actuators()}


@app.get("/api/history/actuators/{idx}")
async def history_actuator_series(idx: int, req: Request, range: str = "day"):
    denied = _require_history_reader(req)
    if denied:
        return denied
    range_name = range if range in ("day", "month", "year") else "day"
    return state_manager.history_manager.get_actuator_series(idx, range_name)


@app.get("/api/history/sessions")
async def history_sessions(
    req: Request,
    type: str = "sauna",
    limit: int = 50,
    offset: int = 0,
):
    denied = _require_history_reader(req)
    if denied:
        return denied
    session_type = type if type in ("sauna", "ir") else "sauna"
    limit = max(1, min(limit, 200))
    offset = max(0, offset)
    return state_manager.sensor_history.get_sessions(session_type, limit=limit, offset=offset)


@app.get("/api/history/{idx}/summary")
async def history_summary(idx: int, req: Request):
    denied = _require_history_reader(req)
    if denied:
        return denied
    return state_manager.sensor_history.get_summary(idx)


@app.get("/api/history/{idx}")
async def history_series(idx: int, req: Request, range: str = "day"):
    denied = _require_history_reader(req)
    if denied:
        return denied
    range_name = range if range in ("day", "month", "year") else "day"
    return state_manager.sensor_history.get_series(idx, range_name)


@app.post("/api/event")
async def inject_event(request: GenericEventRequest, req: Request) -> dict[str, Union[str, Event]]:
    e_type_str = request.type.value if hasattr(request.type, 'value') else str(request.type)

    # Block users/kiosks from performing system-level administration toggles
    admin_only_events = ["CONFIG_RELOAD_REQUESTED", "SYSTEM_SWEEP_REQUESTED", "SIMULATIONS_TOGGLED"]
    if req.state.role != "admin":
        if e_type_str in admin_only_events or e_type_str.endswith("_TOGGLED"):
            return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    try:
        e_type = EventType(request.type)
    except ValueError:
        e_type = request.type

    event: Event = Event(type=e_type, payload=request.payload)
    state_manager.dispatch(event)
    return {"status": "Event dispatched", "event": event}


@app.get("/api/state/sse")
async def sse_state_stream(request: Request):
    """
    Delta SSE stream. Emits only changed domain subtrees after each event queue drain.
    Payload format: {"domain": "<key>", "data": { ... }}
    The frontend fetches /api/state on connect for the full snapshot, then
    applies these partial updates by domain key as they arrive.
    """

    async def event_generator():
        # Track the last emitted snapshot per domain to suppress redundant pushes
        last_domain_snapshots: dict[str, str] = {}
        import time
        last_ping_time = time.time()

        try:
            while not shutdown_event.is_set():
                if await request.is_disconnected():
                    break

                current_state = state_manager.get_state_snapshot()
                data_sent = False

                # Emit only domains whose serialized content has changed since last push
                for domain in ["system", "sensors", "sauna", "ir", "metrics", "hardware", "devices", "device_metadata"]:
                    domain_data = getattr(current_state, domain, None)
                    if domain_data is None:
                        continue

                    # Serialize the domain subtree for diffing
                    if hasattr(domain_data, "model_dump"):
                        domain_json = json.dumps(domain_data.model_dump())
                    else:
                        domain_json = json.dumps(domain_data)

                    if last_domain_snapshots.get(domain) != domain_json:
                        # This is where the data is sent to the frontend, app.js
                        payload = json.dumps({"domain": domain, "data": json.loads(domain_json)})
                        yield f"data: {payload}\n\n"
                        last_domain_snapshots[domain] = domain_json
                        data_sent = True

                # 💓 INTUITIVE APP-LEVEL HEARTBEAT MONITOR
                now = time.time()
                if data_sent:
                    # If live structural state updates went out, they double as our keep-alive
                    last_ping_time = now
                elif now - last_ping_time >= 5.0:
                    # Pipe an explicit, silent data block if the channel remains quiet for 5 seconds
                    ping_payload = json.dumps({"domain": "ping", "data": {}})
                    yield f"data: {ping_payload}\n\n"
                    last_ping_time = now

                await asyncio.sleep(0.5)
        except asyncio.CancelledError:
            pass

    return StreamingResponse(event_generator(), media_type="text/event-stream")


# TIER 3 CACHE-BUSTING MIDDLEWARE
# Intercepts every outgoing HTTP request. If the browser is asking for a frontend asset
# (HTML, JS, CSS), we forcefully inject HTTP headers forbidding the browser from caching it.
@app.middleware("http")
async def add_no_cache_headers(request: Request, call_next):
    response = await call_next(request)

    # Do not mess with API endpoints or SSE streams, only static files.
    if not request.url.path.startswith("/api/"):
        response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "0"
    return response


frontend_path = os.path.join(os.path.dirname(__file__), "frontend")
if os.path.exists(frontend_path):
    app.mount("/", StaticFiles(directory=frontend_path, html=True), name="frontend")
else:
    logger.warning(f"⚠️ Warning: Frontend directory not found at {frontend_path}")