# --- file: main.py ---

# WanOS - Smart Home OS & Sauna Controller
# Copyright (C) 2026 Johan Wannes Hofmans (https://github.com/gitwannes)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

import asyncio
import json
import os
import signal
import jwt
import yaml
from contextlib import asynccontextmanager
from typing import Union, Any, AsyncGenerator, Optional
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse, RedirectResponse, JSONResponse, Response
from pydantic import BaseModel
from fastapi.staticfiles import StaticFiles
from starlette.datastructures import MutableHeaders
from starlette.types import ASGIApp, Receive, Scope, Send
from loguru import logger
from datetime import datetime, timedelta, timezone

# WanOS specific
from core.models import Event, EventType
from core.mqtt_transport import MqttClientManager
from core.mqtt_publisher import MqttPublisher
from core.state_manager import StateManager
from core.sse_hub import sse_hub
from core.config import load_config, AppConfig
from core.automations_store import (
    append_automation,
    automations_from_root,
    delete_automation,
    load_automations_roundtrip,
    read_automations,
    update_automation,
)
from core.events_store import (
    create_user_event,
    delete_event,
    events_by_id_from_root,
    find_event,
    read_events,
    update_event,
    count_system_event_listeners,
    rule_fire_refs_to_event,
    rule_trigger_refs_to_event,
)
from core.automations_fire_status import build_automations_fire_status
from core.event_catalog import (
    to_bus_token,
    normalize_event_name_key,
    SYSTEM_UUID_TO_KEY,
    SYSTEM_UUID_TO_NAME,
)
from core.soft_hide_store import read_soft_hide_entity_ids, write_soft_hide_entity_ids
from core.hue_presets_store import (
    add_preset,
    delete_preset,
    read_presets,
    rename_preset,
    rule_names_using_preset,
)
from core.auto_off_store import read_auto_off_config, write_auto_off_config
from core.auto_off_policy import (
    AUTO_OFF_ALLOWED_TYPES,
    is_auto_off_eligible,
    normalize_minutes,
    sanitize_delay_map,
    sanitize_managed_list,
    sanitize_pertype_map,
)
from core.product_type_policy import (
    PRODUCT_TYPES,
    is_product_type_editable,
    sanitize_product_type_overrides,
)
from core.automations_schema_v2 import (
    is_v2_rule,
    legacy_to_v2,
    ordered_v2_dict,
    validate_v2_entity_ids,
)
from core.automations_api_models import (
    BranchedAutomationRuleRequest,
    FlatAutomationRuleRequest,
    AutomationsRuleIdRequest,
)
from core.logger import setup_wanos_logging, WanosLogger
from hardware.simulator import lab_mode_thermodynamics_loop
from integrations.open_weather import weather_polling_loop
from integrations.zwave import ZWaveJSUIBridge

# Physical Hardware Imports
from hardware.inputs import HardwareInputs
from hardware.sensors import HardwareSensors
from hardware.actuators import HardwareActuators

# Create a global shutdown event kill switch
shutdown_event = asyncio.Event()

# 0. Configure Centralized File Logger
logger.remove()  # 🛑 Silences the default console output entirely
# 0. Initialize WanOS custom Logging
setup_wanos_logging()

# 1. Load and validate the configuration from YAML and .env
config: AppConfig = load_config()

# 2. Inject the config safely into the Local MQTT Transport (local Mosquitto broker)
mqtt_manager: MqttClientManager = MqttClientManager(
    broker_host=config.wanos.mqtt.broker_host,
    port=config.wanos.mqtt.port,
    username=config.wanos.mqtt.username,
    password=config.wanos.mqtt.password
)

# 3. Initialize the Logger and State Manager
wanos_logger: WanosLogger = WanosLogger(mqtt_client=mqtt_manager)
state_manager: StateManager = StateManager(mqtt_client=mqtt_manager, logger=wanos_logger)
state_manager._sse_hub = sse_hub

# 🚀 The absolute first log entry, pulling the dynamic version string generated by the StateManager
logger.info(f"🚀 WanOS booting - {state_manager._state.system.version_full}...")

# 4. Initialize the domain-scoped MQTT Publisher
# ARCHITECTURE NOTE: This is the "WanOS Correspondent". It knows which domain maps to
# which topic, at which cadence. It receives post-drain snapshots from StateManager
# together with the set of changed domains, and routes each to the correct topic.
# The Postman (mqtt_manager) delivers the packets; this layer decides what to write.
mqtt_publisher: MqttPublisher = MqttPublisher(mqtt_client=mqtt_manager)

# 5. Bind the Z-Wave JS UI Bridge
zwave_bridge = ZWaveJSUIBridge(
    state_manager=state_manager,
    mqtt_client=mqtt_manager  # Uses the primary local WanOS broker
)
state_manager.zwave_bridge = zwave_bridge

# 6. Bind the Native RFXCOM Bridge (Dual-Use Architecture)
# Conditionally loaded to prevent crashes if the config block is omitted.
native_rfx_bridge = None
if getattr(config, "rfxcom", None) and getattr(config.rfxcom, "serial_port", None):
    try:
        from integrations.rfxcom import NativeRFXCOMBridge

        native_rfx_bridge = NativeRFXCOMBridge(
            state_manager=state_manager,
            serial_port=config.rfxcom.serial_port
        )
        # Inject into state_manager for UI telemetry tracking
        state_manager.rfxcom_bridge = native_rfx_bridge
    except Exception as e:
        logger.exception(f"CRITICAL: Crash loading NativeRFXCOMBridge: {e}")

# 7. Bind the Local Hue Bridge (API v2)
hue_bridge = None
logger.debug("DIAGNOSTIC: Checking if Hue config exists...")
if getattr(config, "hue", None) and getattr(config.hue, "bridge_ip", None):
    logger.debug(f"DIAGNOSTIC: Hue config found. IP: {config.hue.bridge_ip}. Attempting to import HueLocalBridge...")
    try:
        from integrations.hue import HueLocalBridge
        logger.debug("DIAGNOSTIC: HueLocalBridge imported successfully. Instantiating...")
        hue_bridge = HueLocalBridge(
            state_manager=state_manager,
            config=config
        )
        logger.debug("DIAGNOSTIC: HueLocalBridge instantiated successfully.")
        # Inject into state_manager for UI telemetry tracking
        state_manager.hue_bridge = hue_bridge
    except Exception as e:
        logger.debug(f"DIAGNOSTIC CRITICAL CRASH during Hue init: {e}")
        # import traceback
        # traceback.print_exc()  # Force raw Python stack trace to console
        logger.exception(f"CRITICAL: Crash loading HueLocalBridge: {e}")
else:
    logger.debug("DIAGNOSTIC: Hue config NOT found or missing bridge_ip.")

# 8. Bind the Epson Projector Bridge
epson_bridge = None
if getattr(config, "epson", None) and getattr(config.epson, "ip_address", None):
    try:
        from integrations.epson import EpsonProjector
        epson_bridge = EpsonProjector(host=config.epson.ip_address)
        state_manager.epson_bridge = epson_bridge
        logger.info(f"Epson Projector Bridge initialized at {config.epson.ip_address}")
    except Exception as e:
        logger.exception(f"CRITICAL: Crash loading EpsonProjector: {e}")

# 9. Bind the Physical Hardware Layer
hw_inputs = HardwareInputs(state_manager=state_manager)
hw_sensors = HardwareSensors(state_manager=state_manager)
hw_actuators = HardwareActuators(state_manager=state_manager)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
    """Manages startup and shutdown sequences safely without silent deadlocks."""

    logger.info("Initializing pre-boot sequence...")

    # Intercept the exact CTRL-C signal to instantly drop the SSE stream
    loop = asyncio.get_running_loop()
    try:
        for sig in (signal.SIGINT, signal.SIGTERM):
            original_handler = signal.getsignal(sig)

            def make_handler(orig=original_handler):
                def custom_handler(signum, frame):
                    def _mark():
                        state_manager._shutting_down = True
                        shutdown_event.set()
                    loop.call_soon_threadsafe(_mark)
                    if callable(orig):
                        orig(signum, frame)

                return custom_handler

            signal.signal(sig, make_handler())
    except Exception:
        pass  # Windows compatibility failsafe

    try:
        # 1. Start Network Transports
        logger.info("Connecting to local Mosquitto MQTT Broker...")
        await mqtt_manager.start()

        # 2. Initialize the state engine and wire up the publisher
        await state_manager.start()

        state_manager.mqtt_publisher = mqtt_publisher
        mqtt_publisher.start()

        # Start external bridges
        logger.debug("DIAGNOSTIC: Awaiting zwave_bridge.start()...")
        await zwave_bridge.start()
        logger.debug("DIAGNOSTIC: zwave_bridge.start() completed successfully.")
        if native_rfx_bridge:
            logger.debug("DIAGNOSTIC: Awaiting native_rfx_bridge.start()...")
            try:
                await native_rfx_bridge.start()
                logger.debug("DIAGNOSTIC: native_rfx_bridge.start() completed successfully.")
            except Exception as e:
                logger.debug(f"DIAGNOSTIC CRASH during await native_rfx_bridge.start(): {e}")
                import traceback
                traceback.print_exc()
        if hue_bridge:
            logger.debug("DIAGNOSTIC: Awaiting hue_bridge.start()...")
            try:
                await hue_bridge.start()
                logger.debug("DIAGNOSTIC: hue_bridge.start() completed successfully.")
            except Exception as e:
                logger.debug(f"DIAGNOSTIC CRASH during await hue_bridge.start(): {e}")
                import traceback
                traceback.print_exc()

        # Start Physical Hardware Layer
        logger.info("Initializing Raspberry Pi Hardware Layer...")
        await hw_inputs.start()
        await hw_sensors.start()
        await hw_actuators.start()

        # 3. Seed initial state parameters
        state_manager.dispatch(Event(type=EventType.SYSTEM_READY))
        logger.info("Core systems online. Base state ready.")

        # AUTOSTART SEQUENCE
        # Evaluates .env configuration. Spawns a non-blocking background task to wait
        # 5 seconds for local network sockets to stabilize, then fires the Master Start Sequence.
        if os.getenv("WANOS_AUTOSTART", "False").lower() == "true":
            async def delayed_autostart():
                await asyncio.sleep(5.0)
                logger.info("🚀 Executing automated Master Start Sequence (WANOS_AUTOSTART=True)...")
                # Phase 1: Arm the Brain
                state_manager.dispatch(Event(type=EventType.AUTOMATIONS_TOGGLED, payload={"enabled": True}))
                # Phase 2: Power the Actuators
                state_manager.dispatch(Event(type=EventType.HUE_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.EPSON_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.RFXCOM_TOGGLED, payload={"enabled": True}))
                # Phase 3: Enable Sonos & Onkyo
                state_manager.dispatch(Event(type=EventType.SONOS_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.ONKYO_TOGGLED, payload={"enabled": True}))
                # Phase 4: Enable Z-Wave (may defer silently until MQTT data plane is alive;
                # telemetry auto-recovery arms it when ready — no false "frozen" reject alert).
                state_manager.dispatch(Event(type=EventType.ZWAVE_TOGGLED, payload={"enabled": True}))
                # Phase 5: The OWM Cloud
                state_manager.dispatch(Event(type=EventType.OWM_TOGGLED, payload={"enabled": True}))
                # Phase 6: Arm Hardware Inputs
                state_manager.dispatch(Event(type=EventType.GPIO_INPUT_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.SHT11_TOGGLED, payload={"enabled": True}))
                # Phase 7: Wait for stabilization (Give SHT11 loop time to parse real-world temps)
                await asyncio.sleep(2.0)
                # Phase 8: Synchronization Sweep (Outputs remain safely disarmed until UI manual intervention)
                state_manager.dispatch(Event(type=EventType.SYSTEM_SWEEP_REQUESTED, payload={}))

            asyncio.create_task(delayed_autostart())

        # 4. Start the thermodynamics engine in the background
        logger.info("Simulation engine booting...")
        physics_task = asyncio.create_task(lab_mode_thermodynamics_loop(state_manager))
        logger.info("Simulation engine initialized.")

        # 5. Start the OWM polling loop
        logger.info("[OWM] loop starting...")
        weather_task = asyncio.create_task(weather_polling_loop(state_manager))
        logger.info("[OWM] loop initialized.")

    except Exception as startup_err:
        logger.error(f"Core initialization collapsed: {startup_err}")
        os._exit(1)

    logger.success("Boot sequence complete. HTTP/SSE Web Interface online.")
    yield

    # Shutdown sequence
    logger.warning("Tearing down background engines...")
    state_manager._shutting_down = True
    shutdown_event.set()
    physics_task.cancel()
    weather_task.cancel()
    mqtt_publisher.stop()

    # Stop the physical hardware layer gracefully
    await hw_inputs.stop()
    await hw_sensors.stop()
    await hw_actuators.stop()

    if native_rfx_bridge:
        await native_rfx_bridge.stop()
    if hue_bridge:
        await hue_bridge.stop()
    await zwave_bridge.stop()

    await state_manager.stop()
    await mqtt_manager.stop()
    logger.success("Clean teardown complete. Goodbye.")

# Initialize FastAPI
app: FastAPI = FastAPI(lifespan=lifespan, title="WanOS Backend API")


# Server-Side strike tracker for brute-force protection
failed_attempts: dict[str, dict] = {}


class RbacASGI:
    """
    JWT RBAC as pure ASGI (not BaseHTTPMiddleware).

    FastAPI @app.middleware("http") wraps StreamingResponse. Keep SSE on a
    pass-through ASGI stack so the generator is not cancelled after headers.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return
        request = Request(scope, receive)
        path = request.url.path

        if path.endswith((".js", ".css", ".png", ".ico", ".svg", ".html")) and not path.startswith("/api/"):
            await self.app(scope, receive, send)
            return

        if path == "/":
            query_string = request.url.query
            target_url = f"/login.html?{query_string}" if query_string else "/login.html"
            await RedirectResponse(url=target_url, status_code=302)(scope, receive, send)
            return

        if path == "/api/auth/login":
            await self.app(scope, receive, send)
            return

        token = None
        auth_header = request.headers.get("Authorization")
        if auth_header and auth_header.startswith("Bearer "):
            token = auth_header.split(" ")[1]
        elif request.query_params.get("jwt"):
            token = request.query_params.get("jwt")

        role = None
        if token:
            try:
                payload = jwt.decode(token, config.auth.secret_key, algorithms=["HS256"])
                role = payload.get("role")
            except Exception:
                pass

        if not role and path.startswith("/api/"):
            await JSONResponse(status_code=401, content={"detail": "Unauthorized. Session expired."})(
                scope, receive, send
            )
            return

        request.state.role = role
        await self.app(scope, receive, send)


class NoCacheStaticASGI:
    """Cache-bust static HTML/JS/CSS without wrapping API/SSE streams."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return
        path = scope.get("path") or ""
        if path.startswith("/api/"):
            await self.app(scope, receive, send)
            return

        async def send_with_headers(message: dict) -> None:
            if message["type"] == "http.response.start":
                headers = MutableHeaders(raw=message.setdefault("headers", []))
                headers["Cache-Control"] = (
                    "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
                )
                headers["Pragma"] = "no-cache"
                headers["Expires"] = "0"
            await send(message)

        await self.app(scope, receive, send_with_headers)


class LoginRequest(BaseModel):
    pin: Optional[str] = None
    token: Optional[str] = None


@app.post("/api/auth/login")
async def login(req: LoginRequest, request: Request):
    # Use X-Forwarded-For if available to get the true client IP
    forwarded_for = request.headers.get("x-forwarded-for")
    if forwarded_for:
        client_ip = forwarded_for.split(",")[0].strip()
    else:
        client_ip = request.client.host

    now = datetime.now(timezone.utc)

    # Lazy cleanup: remove expired bans to prevent memory leaks
    expired_ips = [ip for ip, record in failed_attempts.items() if record["lockout_until"] and record["lockout_until"] < now]
    for ip in expired_ips:
        del failed_attempts[ip]

    # 1. Check IP Ban Status
    strike_record = failed_attempts.get(client_ip, {"strikes": 0, "lockout_until": None})
    if strike_record["lockout_until"] and now < strike_record["lockout_until"]:
        mins_left = int((strike_record["lockout_until"] - now).total_seconds() / 60) + 1
        return JSONResponse(status_code=429, content={"error": f"Too many attempts. Locked out for {mins_left} minutes."})

    # 2. Evaluate Credentials
    role = None
    if req.token:
        if req.token == config.auth.user_token: role = "user"
        elif req.token == config.auth.kiosk_token: role = "kiosk"
    elif req.pin:
        if req.pin == config.auth.admin_pin: role = "admin"
        elif req.pin == config.auth.user_pin or req.pin == config.auth.shared_pin: role = "user"

    # 3. Handle Failure
    if not role:
        strike_record["strikes"] += 1
        if strike_record["strikes"] >= 3:
            strike_record["lockout_until"] = now + timedelta(minutes=config.auth.ban_timeout_mins)
            strike_record["strikes"] = 0
            failed_attempts[client_ip] = strike_record
            return JSONResponse(status_code=429, content={"error": f"Too many attempts. Locked out for {config.auth.ban_timeout_mins} minutes."})

        failed_attempts[client_ip] = strike_record
        return JSONResponse(status_code=401, content={"error": "Invalid PIN."})

    # 4. Success -> Clear strikes & Issue JWT in Payload
    if client_ip in failed_attempts:
        del failed_attempts[client_ip]

    expiration = now + timedelta(days=config.auth.cookie_expiry_days)
    jwt_payload = {"role": role, "exp": expiration}
    token = jwt.encode(jwt_payload, config.auth.secret_key, algorithm="HS256")

    target_url = "/deviceexplorer.html" if role in ["admin", "user"] else "/kiosk.html"

    # Send the token directly in the JSON response body
    return JSONResponse(content={"status": "Success", "role": role, "redirect": target_url, "token": token})


@app.post("/api/auth/logout")
async def logout():
    # Cookie deletion removed. The frontend is now responsible for wiping its local tab memory.
    return JSONResponse(content={"status": "Logged out"})


class GenericEventRequest(BaseModel):
    type: Union[EventType, str]
    payload: dict[str, Any] = {}


class ZwaveConfigRequest(BaseModel):
    yaml_content: str


@app.post("/api/config/zwave")
async def update_zwave_config(request: ZwaveConfigRequest, req: Request):
    """Directly injects the YAML payload from the UI into the local server file."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    # Validate YAML content before saving
    try:
        yaml.safe_load(request.yaml_content)
    except yaml.YAMLError as e:
        logger.error(f"Invalid YAML payload received: {e}")
        return JSONResponse(status_code=400, content={"error": "Invalid YAML format."})

    try:
        file_path = os.path.join(os.path.dirname(__file__), "config_zwave.auto.yaml")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(request.yaml_content)
        return {"status": "Success", "message": "Z-Wave configuration written to disk."}
    except Exception as e:
        logger.error(f"Failed to write Z-Wave config from UI: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to save configuration file on server."})


@app.get("/api/automations")
async def list_automations(req: Request) -> dict[str, Any]:
    """Admin: list automations as schema v2 (legacy on disk is converted for the editor)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    return await asyncio.to_thread(_list_automations_payload)


@app.get("/api/automations/fire-status")
async def automations_fire_status(req: Request) -> dict[str, Any]:
    """
    B10F: today's fire status for schedule SEs + Sauna/IR OFF (admin).

    FE renders Will fire at / Has fired at / Doesn't fire today; no client schedule math.
    """
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    tm = getattr(state_manager, "_timer_manager", None)
    sauna_armed = bool(tm and tm.is_scheduled("sauna_main"))
    ir_armed = bool(tm and tm.is_scheduled("ir_main"))
    return build_automations_fire_status(
        state_manager._state,
        sauna_timer_armed=sauna_armed,
        ir_timer_armed=ir_armed,
    )


def _log_library_crud(kind: str, name: str, verb: str) -> None:
    """B10F: INFO line in wanos.log for Automations Library CRUD."""
    label = (name or "").strip() or "(unnamed)"
    logger.info(f'{kind} "{label}" {verb}')


def _log_hue_preset_crud(name: str, verb: str) -> None:
    """B9A: INFO line in wanos.log for Hue preset CRUD (display name only)."""
    label = (name or "").strip() or "(unnamed)"
    logger.info(f'hue preset "{label}" {verb}')


def _rule_log_kind(rule: dict[str, Any]) -> str:
    """user rule vs system rule from primary trigger event origin."""
    eid = _primary_trigger_event_id(rule)
    if eid and eid in SYSTEM_UUID_TO_KEY:
        return "system rule"
    return "user rule"


def _primary_trigger_event_id(rule: dict[str, Any]) -> Optional[str]:
    """First event UUID on B19 event Compares or legacy v2 trigger."""
    from core.automations_schema_b19 import primary_event_id_from_rule
    return primary_event_id_from_rule(rule)


def _bind_sr_name_to_se_catalog(
    rule: dict[str, Any],
    *,
    events_by_id: Optional[dict[str, dict[str, Any]]] = None,
) -> None:
    """
    SR invariant: rule name always equals companion SE catalog name.

    On automations POST/PUT, if the primary wake event is a system event, overwrite
    ``name`` from the live catalog (YAML events:) or seed constant so YAML cannot
    drift (e.g. old free-text SR titles).

    B10H: pass ``events_by_id`` on list hot paths to avoid N+1 YAML reloads.
    """
    eid = _primary_trigger_event_id(rule)
    if not eid or eid not in SYSTEM_UUID_TO_KEY:
        return
    if events_by_id is not None:
        cat = events_by_id.get(eid)
    else:
        cat = find_event(eid)
    cat_name = ""
    if isinstance(cat, dict) and cat.get("name"):
        cat_name = str(cat["name"]).strip()
    if not cat_name:
        cat_name = str(SYSTEM_UUID_TO_NAME.get(eid) or "").strip()
    if cat_name:
        rule["name"] = cat_name


def _persist_automation_payload(rule: dict[str, Any]) -> dict[str, Any]:
    """
    B19: persist Domoticz branch shape only. Legacy trigger+cases / Y1 / flat → 400.
    """
    import uuid

    from core.automations_schema_b19 import (
        is_branch_rule,
        is_legacy_cases_rule,
        normalize_branch_rule,
        ordered_branch_dict,
        validate_branch_entity_ids,
        validate_branch_rule_for_enable,
    )

    if is_legacy_cases_rule(rule) or (
        isinstance(rule, dict)
        and ("trigger" in rule or "cases" in rule)
        and not is_branch_rule(rule)
    ):
        raise ValueError(
            "Legacy trigger+cases authoring is retired (B19). "
            "Use branches (If/Do). Multi-device OR leftovers wait Ship B4/H4."
        )
    if ("on" in rule) or ("off" in rule) or (
        not is_branch_rule(rule) and ("conditions" in rule or "actions" in rule)
        and "branches" not in rule
    ):
        raise ValueError(
            "Legacy Y1/flat automation payloads are retired (B19). Use branches."
        )

    if not is_branch_rule(rule):
        raise ValueError("Automation must use branches: [{ when, conditions, actions }, …].")

    br = ordered_branch_dict(normalize_branch_rule(rule))
    if not br.get("id"):
        br["id"] = str(uuid.uuid4())
    if "enabled" not in br:
        br["enabled"] = True
    _bind_sr_name_to_se_catalog(br)
    validate_branch_entity_ids(br)
    enable_err = validate_branch_rule_for_enable(br)
    if br.get("enabled", True) is not False and enable_err:
        raise ValueError(enable_err)
    if enable_err and br.get("enabled", True) is False:
        # Disabled invalid drafts are allowed (locked B19).
        pass
    return br


def _assert_one_system_listener(rule: dict[str, Any]) -> Optional[str]:
    """
    B10E: at most one SR may listen to a given system event (SE).
    Returns an error message or None.
    """
    eid = _primary_trigger_event_id(rule)
    if not eid or eid not in SYSTEM_UUID_TO_KEY:
        return None
    exclude = str(rule.get("id") or "") or None
    if count_system_event_listeners(eid, exclude_rule_id=exclude) >= 1:
        return (
            f"System event already has a listening rule (SR) "
            f"(one flow per system event). Event id={eid}."
        )
    return None


def _assert_u_rule_disable_allowed(rule: dict[str, Any]) -> Optional[str]:
    """
    B10E: cannot disable a user-event rule (UR) while its trigger UE is fire-referenced.
    Returns an error message or None. SR disable is always allowed here.
    """
    if rule.get("enabled", True) is not False:
        return None
    eid = _primary_trigger_event_id(rule)
    if not eid or eid in SYSTEM_UUID_TO_KEY:
        return None
    fire_refs = rule_fire_refs_to_event(eid)
    if not fire_refs:
        return None
    return (
        "Cannot disable: trigger event is fired as action by: "
        + ", ".join(fire_refs)
    )


def _automation_name_clash(name: str, exclude_id: Optional[str] = None) -> Optional[str]:
    """
    B10D: return conflicting rule id if name collides (trim + casefold), else None.
    Same-id update may keep its own name (exclude_id).
    """
    needle = normalize_event_name_key(name)  # trim + casefold helper
    if not needle:
        return "empty"
    for row in read_automations():
        if not isinstance(row, dict):
            continue
        rid = str(row.get("id") or "")
        if exclude_id and rid == exclude_id:
            continue
        if normalize_event_name_key(str(row.get("name") or "")) == needle:
            return rid or "?"
    return None


@app.post("/api/automations")
async def create_automation(rule: dict[str, Any], req: Request) -> dict[str, Any]:
    """Admin: create automation — persisted as schema v2 only."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    try:
        new_rule = _persist_automation_payload(rule)
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Invalid automation payload: {e}"})

    clash = _automation_name_clash(str(new_rule.get("name") or ""))
    if clash == "empty":
        return JSONResponse(status_code=400, content={"error": "Automation name is required."})
    if clash:
        return JSONResponse(
            status_code=409,
            content={"error": f"Automation name already in use (id={clash})."},
        )

    sys_err = _assert_one_system_listener(new_rule)
    if sys_err:
        return JSONResponse(status_code=409, content={"error": sys_err})

    disable_err = _assert_u_rule_disable_allowed(new_rule)
    if disable_err:
        return JSONResponse(status_code=409, content={"error": disable_err})

    current = read_automations()
    if any(isinstance(r, dict) and r.get("id") == new_rule["id"] for r in current if isinstance(r, dict)):
        return JSONResponse(status_code=409, content={"error": "Duplicate automation id."})

    append_automation(new_rule)
    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    _log_library_crud(_rule_log_kind(new_rule), str(new_rule.get("name") or ""), "added")
    return {"status": "Success", "automation": new_rule}


@app.put("/api/automations")
async def update_automation_api(rule: dict[str, Any], req: Request) -> dict[str, Any]:
    """Admin: replace automation by id — persisted as schema v2 only."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    try:
        dumped = _persist_automation_payload(rule)
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Invalid automation payload: {e}"})

    if not dumped.get("id"):
        return JSONResponse(status_code=400, content={"error": "PUT requires a stable automation rule `id`."})

    clash = _automation_name_clash(str(dumped.get("name") or ""), exclude_id=str(dumped["id"]))
    if clash == "empty":
        return JSONResponse(status_code=400, content={"error": "Automation name is required."})
    if clash:
        return JSONResponse(
            status_code=409,
            content={"error": f"Automation name already in use (id={clash})."},
        )

    sys_err = _assert_one_system_listener(dumped)
    if sys_err:
        return JSONResponse(status_code=409, content={"error": sys_err})

    disable_err = _assert_u_rule_disable_allowed(dumped)
    if disable_err:
        return JSONResponse(status_code=409, content={"error": disable_err})

    if not update_automation(dumped["id"], dumped):
        return JSONResponse(status_code=404, content={"error": f"Automation id '{dumped['id']}' not found."})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    _log_library_crud(_rule_log_kind(dumped), str(dumped.get("name") or ""), "changed")
    return {"status": "Success", "automation": dumped}


@app.delete("/api/automations")
async def delete_automation_api(req_body: AutomationsRuleIdRequest, req: Request) -> dict[str, Any]:
    """Admin: delete an automation rule by id from automations.auto.yaml."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    # Snapshot name/kind for B10F CRUD INFO before remove.
    prior: Optional[dict[str, Any]] = None
    for row in read_automations():
        if isinstance(row, dict) and str(row.get("id") or "") == str(req_body.id):
            prior = row
            break

    if not delete_automation(req_body.id):
        return JSONResponse(status_code=404, content={"error": f"Automation id '{req_body.id}' not found."})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    if prior:
        try:
            _log_library_crud(
                _rule_log_kind(dict(prior)),
                str(prior.get("name") or ""),
                "deleted",
            )
        except Exception:
            _log_library_crud("user rule", str(prior.get("name") or req_body.id), "deleted")
    return {"status": "Success"}


class EventsIdRequest(BaseModel):
    """DELETE /api/events body — mirror AutomationsRuleIdRequest."""
    id: str


@app.get("/api/events")
async def list_events_api(req: Request) -> dict[str, Any]:
    """Admin: list events catalog rows (read-only; Y1 seeds merged at boot via load_config)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    try:
        return await asyncio.to_thread(_list_events_payload)
    except FileNotFoundError as e:
        return JSONResponse(status_code=404, content={"error": str(e)})
    except Exception as e:
        return JSONResponse(status_code=500, content={"error": f"Failed to read events catalog: {e}"})


@app.post("/api/events")
async def create_event_api(body: dict[str, Any], req: Request) -> dict[str, Any]:
    """Admin: create a user event row (server assigns UUID)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    try:
        row = create_user_event(
            str(body.get("name") or ""),
            show_on_dashboard=bool(body.get("show_on_dashboard", False)),
            require_confirmation=bool(body.get("require_confirmation", False)),
            enabled=bool(body.get("enabled", True)),
        )
    except ValueError as e:
        msg = str(e)
        code = 409 if "already in use" in msg or "Duplicate event id" in msg else 400
        return JSONResponse(status_code=code, content={"error": msg})
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Invalid event payload: {e}"})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    _log_library_crud("user event", str(row.get("name") or ""), "added")
    return {"status": "Success", "event": row}


@app.put("/api/events")
async def update_event_api(body: dict[str, Any], req: Request) -> dict[str, Any]:
    """Admin: replace event by id (B10E: system dashboard rejected; confirm coerced)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    try:
        row = update_event(body)
    except KeyError as e:
        return JSONResponse(status_code=404, content={"error": str(e)})
    except ValueError as e:
        msg = str(e)
        code = 409 if "already in use" in msg or "Cannot disable" in msg else 400
        return JSONResponse(status_code=code, content={"error": msg})
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Invalid event payload: {e}"})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    # System events are largely immutable; still log when a write succeeds.
    kind = "system event" if str(row.get("id") or "") in SYSTEM_UUID_TO_KEY else "user event"
    _log_library_crud(kind, str(row.get("name") or ""), "changed")
    return {"status": "Success", "event": row}


@app.get("/api/events/{event_id}/usages")
async def event_usages_api(event_id: str, req: Request) -> dict[str, Any]:
    """
    Admin: Show usages — rules that listen (trigger) OR fire this event.
    Both sides block user-event disable; UI lists the union of names.
    """
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    listened_by = rule_trigger_refs_to_event(event_id)
    fired_by = rule_fire_refs_to_event(event_id)
    # Stable unique union (listeners first, then fire-only names).
    seen: set[str] = set()
    used_by: list[str] = []
    for nm in listened_by + fired_by:
        if nm not in seen:
            seen.add(nm)
            used_by.append(nm)
    return {
        "event_id": event_id,
        "listened_by": listened_by,
        "fired_by": fired_by,
        "used_by": used_by,
    }


@app.delete("/api/events")
async def delete_event_api(req_body: EventsIdRequest, req: Request) -> dict[str, Any]:
    """Admin: delete a user event by id (guards → 409)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    prior = find_event(req_body.id)
    prior_name = ""
    if isinstance(prior, dict):
        prior_name = str(prior.get("name") or "")
    try:
        delete_event(req_body.id)
    except KeyError as e:
        return JSONResponse(status_code=404, content={"error": str(e)})
    except ValueError as e:
        return JSONResponse(status_code=409, content={"error": str(e)})
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": str(e)})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    _log_library_crud("user event", prior_name or str(req_body.id), "deleted")
    return {"status": "Success"}


class SoftHidePutRequest(BaseModel):
    entity_ids: list[str]


@app.get("/api/soft-hide")
async def get_soft_hide(req: Request) -> dict[str, Any]:
    """Admin: list soft-hidden entity_ids (deviceexplorer_hide)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    return {"entity_ids": read_soft_hide_entity_ids()}


@app.put("/api/soft-hide")
async def put_soft_hide(body: SoftHidePutRequest, req: Request) -> dict[str, Any]:
    """Admin: replace soft-hide list; surgical write + hot-reload."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    # Validate known eids against live registry when available
    unknown: list[str] = []
    denied: list[str] = []
    for raw in body.entity_ids:
        eid = str(raw).strip()
        if not eid:
            continue
        if is_hard_deny_entity_id(eid):
            denied.append(eid)
            continue
        if state_manager.resolve_entity_id(eid) is None:
            unknown.append(eid)
    if denied:
        return JSONResponse(
            status_code=400,
            content={"error": f"Hard-deny entity_ids not allowed: {', '.join(denied)}"},
        )
    if unknown:
        return JSONResponse(
            status_code=400,
            content={"error": f"Unknown entity_ids: {', '.join(unknown)}"},
        )

    try:
        written = write_soft_hide_entity_ids(body.entity_ids)
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})
    except Exception as e:
        logger.error(f"soft-hide write failed: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to write soft-hide list."})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    return {"status": "Success", "entity_ids": written}


class HuePresetCreateRequest(BaseModel):
    name: str
    bri: int
    xy: Optional[list[float]] = None
    rgb: Optional[str] = None


class HuePresetRenameRequest(BaseModel):
    name: str


@app.get("/api/hue-presets")
async def get_hue_presets(req: Request) -> dict[str, Any]:
    """Admin: list hue.presets (+ usage rule names per key)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    presets = read_presets()
    usages = {k: rule_names_using_preset(k) for k in presets}
    return {"presets": presets, "usages": usages}


@app.post("/api/hue-presets")
async def post_hue_preset(body: HuePresetCreateRequest, req: Request) -> dict[str, Any]:
    """Admin: add preset from current colour (new key only)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    if body.xy is None and not body.rgb:
        return JSONResponse(status_code=400, content={"error": "xy or rgb required"})
    try:
        key, entry = add_preset(
            name=body.name,
            bri=body.bri,
            xy=list(body.xy) if body.xy is not None else None,
            rgb=body.rgb,
        )
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})
    except Exception as e:
        logger.error(f"hue-presets create failed: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to create preset."})
    _log_hue_preset_crud(str(body.name), "added")
    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api", "scope": "hue_presets"}))
    return {"status": "Success", "key": key, "preset": entry}


@app.put("/api/hue-presets/{key}")
async def put_hue_preset(key: str, body: HuePresetRenameRequest, req: Request) -> dict[str, Any]:
    """Admin: rename display name only (key immutable)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    try:
        entry = rename_preset(key, body.name)
    except KeyError as e:
        return JSONResponse(status_code=404, content={"error": str(e)})
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})
    except Exception as e:
        logger.error(f"hue-presets rename failed: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to rename preset."})
    _log_hue_preset_crud(str(body.name), "renamed")
    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api", "scope": "hue_presets"}))
    return {"status": "Success", "key": key, "preset": entry}


@app.delete("/api/hue-presets/{key}")
async def delete_hue_preset(key: str, req: Request) -> dict[str, Any]:
    """Admin: delete preset; 409 if automations still reference the key."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    usages = rule_names_using_preset(key)
    if usages:
        return JSONResponse(
            status_code=409,
            content={"error": "Preset in use", "usages": usages},
        )
    presets_before = read_presets()
    prior = presets_before.get(key) if isinstance(presets_before, dict) else None
    prior_name = str((prior or {}).get("name") or key)
    try:
        delete_preset(key)
    except KeyError as e:
        return JSONResponse(status_code=404, content={"error": str(e)})
    except ValueError as e:
        return JSONResponse(status_code=409, content={"error": str(e), "usages": usages})
    except Exception as e:
        logger.error(f"hue-presets delete failed: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to delete preset."})
    _log_hue_preset_crud(prior_name, "deleted")
    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api", "scope": "hue_presets"}))
    return {"status": "Success", "key": key}


class AutoOffPutRequest(BaseModel):
    managed_auto_off: list[str] = []
    default_auto_off_minutes: int = 300
    default_pertype_auto_off_minutes: dict[str, int] = {}
    auto_off_delays: dict[str, int] = {}
    device_product_types: dict[str, str] = {}


def _live_meta_for_eid(eid: str) -> dict[str, Any]:
    idx = state_manager.resolve_entity_id(eid)
    if idx is None:
        return {}
    meta = state_manager.get_state_snapshot().device_metadata.get(idx) or {}
    return meta if isinstance(meta, dict) else {}


def _live_type_for_eid(eid: str) -> Optional[str]:
    meta = _live_meta_for_eid(eid)
    if meta.get("type"):
        return str(meta.get("type"))
    return None


def _live_origin_for_eid(eid: str) -> Optional[str]:
    meta = _live_meta_for_eid(eid)
    if meta.get("origin"):
        return str(meta.get("origin"))
    return None


@app.get("/api/auto-off-timer")
async def get_auto_off_timer(req: Request) -> dict[str, Any]:
    """Admin: read auto_off_devices + device_product_types (Timers & types)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    return read_auto_off_config()


@app.put("/api/auto-off-timer")
async def put_auto_off_timer(body: AutoOffPutRequest, req: Request) -> dict[str, Any]:
    """Admin: full-replace auto_off_devices + device_product_types; scoped reload."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    try:
        managed = sanitize_managed_list(body.managed_auto_off)
        general = normalize_minutes(body.default_auto_off_minutes)
        pertype = sanitize_pertype_map(body.default_pertype_auto_off_minutes)
        delays = sanitize_delay_map(body.auto_off_delays)
        product_types = sanitize_product_type_overrides(body.device_product_types)
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})

    managed_set = set(managed)
    unknown: list[str] = []
    ineligible: list[str] = []
    overrides_cfg = getattr(state_manager._config, "device_product_types", None) or {}
    for eid in managed:
        if state_manager.resolve_entity_id(eid) is None:
            unknown.append(eid)
            continue
        dtype = _live_type_for_eid(eid)
        origin = _live_origin_for_eid(eid)
        if not is_auto_off_eligible(
            eid, dtype, origin=origin, product_type_overrides=product_types or overrides_cfg
        ):
            ineligible.append(eid)
    for eid in delays:
        if eid not in managed_set:
            return JSONResponse(
                status_code=400,
                content={"error": f"auto_off_delays orphan '{eid}' (must be in managed_auto_off)"},
            )
        if state_manager.resolve_entity_id(eid) is None and eid not in unknown:
            unknown.append(eid)
    bad_types = [t for t in pertype if t not in AUTO_OFF_ALLOWED_TYPES]
    if bad_types:
        return JSONResponse(
            status_code=400,
            content={"error": f"Invalid type keys: {', '.join(bad_types)}"},
        )
    bad_product: list[str] = []
    for eid, val in product_types.items():
        if state_manager.resolve_entity_id(eid) is None:
            bad_product.append(f"{eid} (unknown)")
            continue
        if val not in PRODUCT_TYPES:
            bad_product.append(f"{eid} (invalid value '{val}')")
            continue
        dtype = _live_type_for_eid(eid)
        origin = _live_origin_for_eid(eid)
        if not is_product_type_editable(eid, origin=origin, device_type=dtype):
            bad_product.append(f"{eid} (not editable)")
    if bad_product:
        return JSONResponse(
            status_code=400,
            content={"error": f"Invalid device_product_types: {', '.join(bad_product)}"},
        )
    if unknown:
        return JSONResponse(
            status_code=400,
            content={"error": f"Unknown entity_ids: {', '.join(unknown)}"},
        )
    if ineligible:
        return JSONResponse(
            status_code=400,
            content={"error": f"Ineligible entity_ids: {', '.join(ineligible)}"},
        )

    try:
        written = write_auto_off_config(
            managed_auto_off=managed,
            default_auto_off_minutes=general,
            default_pertype_auto_off_minutes=pertype,
            auto_off_delays=delays,
            device_product_types=product_types,
        )
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})
    except Exception as e:
        logger.error(f"auto-off-timer write failed: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to write auto-off config."})

    state_manager.dispatch(
        Event(
            type=EventType.CONFIG_RELOAD_REQUESTED,
            payload={"source": "api", "scope": "timers_types"},
        )
    )
    return {"status": "Success", **written}


def _build_state_api_payload() -> dict[str, Any]:
    """Cached model_dump when available (B10H); else deep snapshot."""
    return state_manager.get_api_state_payload()


def _list_automations_payload() -> dict[str, Any]:
    """Sync automations list for GET /api/automations (B10H: one YAML load, no N+1 bind)."""
    from core.automations_schema_b19 import is_branch_rule, ordered_branch_dict, normalize_branch_rule

    root, _ = load_automations_roundtrip()
    catalog = events_by_id_from_root(root)
    out: list[dict[str, Any]] = []
    for r in automations_from_root(root):
        if not isinstance(r, dict):
            continue
        if is_branch_rule(r):
            try:
                row = ordered_branch_dict(normalize_branch_rule(dict(r)))
            except ValueError:
                row = dict(r)
        else:
            # Cutover window: still list legacy v2 until migrator runs.
            row = ordered_v2_dict(legacy_to_v2(dict(r)))
        _bind_sr_name_to_se_catalog(row, events_by_id=catalog)
        out.append(row)
    return {"automations": out}


def _list_events_payload() -> dict[str, Any]:
    """Sync events list for GET /api/events (read-only; seeds merged at boot in load_config)."""
    return {"events": read_events()}


@app.get("/api/state")
async def get_state() -> dict[str, Any]:
    return await asyncio.to_thread(_build_state_api_payload)


@app.get("/api/debug/entity-registry-check")
async def debug_entity_registry_check(req: Request) -> dict[str, Any]:
    """Admin Debug: entity_id / automation consistency checks (keep after cutover)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    from core.entity_registry_check import run_entity_cutover_checks

    report = run_entity_cutover_checks(
        device_metadata=state_manager.get_state_snapshot().device_metadata,
    )
    return report


@app.get("/api/admin/entity-id-list")
async def admin_entity_id_list(req: Request):
    """Admin: download live entity_id authoring list (core.entity_id_list)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    from core.entity_id_list import generate_entity_id_list_text

    try:
        text = generate_entity_id_list_text()
    except FileNotFoundError as e:
        return JSONResponse(status_code=404, content={"error": str(e)})
    except Exception as e:
        logger.error(f"Failed to generate entity_id list: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to generate entity_id list."})

    return Response(
        content=text,
        media_type="text/plain; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="entity_id-list.txt"'},
    )


@app.post("/api/admin/restart")
async def admin_restart_wanos(req: Request) -> JSONResponse:
    """Admin: restart WanOS systemd unit (service only — not the host).

    Requires passwordless sudo for:
      /usr/bin/systemctl restart wanos.service
    Returns 202 when the restart command is accepted; UI reconnects after the unit is back.
    """
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    cmd = ["sudo", "-n", "/usr/bin/systemctl", "restart", "wanos.service"]
    try:
        # Fire-and-forget-ish: accept quickly; systemd will kill this process during restart.
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        # Brief wait so we can surface sudo/NOPASSWD failures before the unit dies.
        try:
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=3.0)
        except asyncio.TimeoutError:
            # Restart likely accepted and this process is being stopped — treat as success.
            logger.info("admin restart: systemctl still running after 3s (likely restarting)")
            return JSONResponse(status_code=202, content={"ok": True, "message": "Restart accepted"})

        if proc.returncode != 0:
            err = (stderr or b"").decode("utf-8", errors="replace").strip()
            out = (stdout or b"").decode("utf-8", errors="replace").strip()
            detail = err or out or f"systemctl exit {proc.returncode}"
            logger.error(f"admin restart failed: {detail}")
            return JSONResponse(
                status_code=500,
                content={
                    "error": (
                        "Failed to restart WanOS service. "
                        "Check passwordless sudo for "
                        "'systemctl restart wanos.service'. "
                        f"Detail: {detail}"
                    )
                },
            )
        logger.info("admin restart: systemctl restart wanos.service accepted")
        return JSONResponse(status_code=202, content={"ok": True, "message": "Restart accepted"})
    except Exception as e:
        logger.error(f"admin restart exception: {e}")
        return JSONResponse(status_code=500, content={"error": f"Restart failed: {e}"})


def _require_history_reader(req: Request):
    """Device/session history is available to admin and user roles."""
    if req.state.role not in ("admin", "user"):
        return JSONResponse(status_code=403, content={"error": "Forbidden: Login required."})
    return None


@app.get("/api/history/sensors")
async def history_sensors(req: Request):
    denied = _require_history_reader(req)
    if denied:
        return denied
    return {"sensors": state_manager.sensor_history.list_sensors()}


@app.get("/api/history/actuators")
async def history_actuators(req: Request):
    denied = _require_history_reader(req)
    if denied:
        return denied
    return {"actuators": state_manager.history_manager.list_actuators()}


@app.get("/api/history/actuators/{idx}")
async def history_actuator_series(idx: int, req: Request, range: str = "day"):
    denied = _require_history_reader(req)
    if denied:
        return denied
    range_name = range if range in ("day", "month", "year") else "day"
    return state_manager.history_manager.get_actuator_series(idx, range_name)


@app.get("/api/history/sessions")
async def history_sessions(
    req: Request,
    type: str = "sauna",
    limit: int = 50,
    offset: int = 0,
):
    denied = _require_history_reader(req)
    if denied:
        return denied
    session_type = type if type in ("sauna", "ir") else "sauna"
    limit = max(1, min(limit, 200))
    offset = max(0, offset)
    return state_manager.sensor_history.get_sessions(session_type, limit=limit, offset=offset)


@app.get("/api/history/{idx}/summary")
async def history_summary(idx: int, req: Request):
    denied = _require_history_reader(req)
    if denied:
        return denied
    return state_manager.sensor_history.get_summary(idx)


@app.get("/api/history/{idx}")
async def history_series(idx: int, req: Request, range: str = "day"):
    denied = _require_history_reader(req)
    if denied:
        return denied
    range_name = range if range in ("day", "month", "year") else "day"
    return state_manager.sensor_history.get_series(idx, range_name)


@app.post("/api/event")
async def inject_event(request: GenericEventRequest, req: Request) -> dict[str, Union[str, Event]]:
    e_type_str = request.type.value if hasattr(request.type, 'value') else str(request.type)
    # Normalize catalog keys → UUID before admin checks / dispatch.
    bus_token = to_bus_token(e_type_str)

    # Block users/kiosks from performing system-level administration toggles
    admin_only_events = ["CONFIG_RELOAD_REQUESTED", "SYSTEM_SWEEP_REQUESTED", "SIMULATIONS_TOGGLED"]
    if req.state.role != "admin":
        if e_type_str in admin_only_events or e_type_str.endswith("_TOGGLED"):
            return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    try:
        e_type: Any = EventType(bus_token)
    except ValueError:
        e_type = bus_token

    event: Event = Event(type=e_type, payload=request.payload)
    state_manager.dispatch(event)
    return {"status": "Event dispatched", "event": event}


@app.get("/api/state/sse")
async def sse_state_stream(request: Request):
    """
    Delta SSE stream. Emits domain subtrees when state changes (B10H event-driven hub).
    Payload format: {"domain": "<key>", "data": { ... }}
    The frontend fetches /api/state on connect for the full snapshot, then
    applies these partial updates by domain key as they arrive.

    First byte is an immediate ping: behind nginx, awaiting is_disconnected()
    before any yield returned 200 + empty body (~10 ms) and EventSource.onerror.
    X-Accel-Buffering tells nginx 1.18 not to buffer the stream.
    """
    import time

    def _ping_line() -> str:
        return f"data: {json.dumps({'domain': 'ping', 'data': {}})}\n\n"

    async def event_generator() -> AsyncGenerator[str, None]:
        client = await sse_hub.subscribe()
        last_ping_time = time.time()
        try:
            yield _ping_line()
            while not shutdown_event.is_set():
                try:
                    line = await asyncio.wait_for(client.queue.get(), timeout=5.0)
                    yield line
                    last_ping_time = time.time()
                except asyncio.TimeoutError:
                    now = time.time()
                    if now - last_ping_time >= 5.0:
                        yield _ping_line()
                        last_ping_time = now
                if await request.is_disconnected():
                    break
        except asyncio.CancelledError:
            pass
        finally:
            await sse_hub.unsubscribe(client)

    # Do not send Connection: keep-alive. HTTP/2 forbids hop-by-hop headers;
    # nginx 1.18 + listen http2 then yields Chrome net::ERR_HTTP2_PROTOCOL_ERROR
    # (200) and EventSource.onerror. Keep-alive is implicit for HTTP/1.1 proxy.
    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


frontend_path = os.path.join(os.path.dirname(__file__), "frontend")
if os.path.exists(frontend_path):
    app.mount("/", StaticFiles(directory=frontend_path, html=True), name="frontend")
else:
    logger.warning(f"⚠️ Warning: Frontend directory not found at {frontend_path}")

# Last added = outermost. RBAC first; static no-cache must not wrap SSE
# (BaseHTTPMiddleware is unsafe for StreamingResponse).
app.add_middleware(NoCacheStaticASGI)
app.add_middleware(RbacASGI)