# --- file: main.py ---

# WanOS - Smart Home OS & Sauna Controller
# Copyright (C) 2026 Johan Wannes Hofmans (https://github.com/gitwannes)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

import asyncio
import json
import os
import signal
import jwt
import yaml
from contextlib import asynccontextmanager
from typing import Union, Any, AsyncGenerator, Optional
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse, RedirectResponse, JSONResponse, Response
from pydantic import BaseModel
from fastapi.staticfiles import StaticFiles
from loguru import logger
from datetime import datetime, timedelta, timezone

# WanOS specific
from core.models import Event, EventType
from core.mqtt_transport import MqttClientManager
from core.mqtt_publisher import MqttPublisher
from core.state_manager import StateManager
from core.config import load_config, AppConfig
from core.automations_store import (
    append_automation,
    delete_automation,
    read_automations,
    update_automation,
)
from core.events_store import (
    create_user_event,
    delete_event,
    find_event,
    merge_system_seeds_into_yaml,
    read_events,
    update_event,
    count_system_event_listeners,
    rule_fire_refs_to_event,
    rule_trigger_refs_to_event,
)
from core.automations_fire_status import build_automations_fire_status
from core.event_catalog import (
    to_bus_token,
    normalize_event_name_key,
    SYSTEM_UUID_TO_KEY,
    SYSTEM_UUID_TO_NAME,
)
from core.soft_hide_store import read_soft_hide_entity_ids, write_soft_hide_entity_ids
from core.auto_off_store import read_auto_off_config, write_auto_off_config
from core.auto_off_policy import (
    AUTO_OFF_ALLOWED_TYPES,
    is_auto_off_eligible,
    normalize_minutes,
    sanitize_delay_map,
    sanitize_managed_list,
    sanitize_pertype_map,
)
from core.well_known_entities import is_hard_deny_entity_id
from core.automations_schema_v2 import (
    is_v2_rule,
    legacy_to_v2,
    ordered_v2_dict,
    validate_v2_entity_ids,
)
from core.automations_api_models import (
    BranchedAutomationRuleRequest,
    FlatAutomationRuleRequest,
    AutomationsRuleIdRequest,
)
from core.logger import setup_wanos_logging, WanosLogger
from hardware.simulator import lab_mode_thermodynamics_loop
from integrations.open_weather import weather_polling_loop
from integrations.zwave import ZWaveJSUIBridge

# Physical Hardware Imports
from hardware.inputs import HardwareInputs
from hardware.sensors import HardwareSensors
from hardware.actuators import HardwareActuators

# Create a global shutdown event kill switch
shutdown_event = asyncio.Event()

# 0. Configure Centralized File Logger
logger.remove()  # 🛑 Silences the default console output entirely
# 0. Initialize WanOS custom Logging
setup_wanos_logging()

# 1. Load and validate the configuration from YAML and .env
config: AppConfig = load_config()

# 2. Inject the config safely into the Local MQTT Transport (local Mosquitto broker)
mqtt_manager: MqttClientManager = MqttClientManager(
    broker_host=config.wanos.mqtt.broker_host,
    port=config.wanos.mqtt.port,
    username=config.wanos.mqtt.username,
    password=config.wanos.mqtt.password
)

# 3. Initialize the Logger and State Manager
wanos_logger: WanosLogger = WanosLogger(mqtt_client=mqtt_manager)
state_manager: StateManager = StateManager(mqtt_client=mqtt_manager, logger=wanos_logger)

# 🚀 The absolute first log entry, pulling the dynamic version string generated by the StateManager
logger.info(f"🚀 WanOS booting - {state_manager._state.system.version_full}...")

# 4. Initialize the domain-scoped MQTT Publisher
# ARCHITECTURE NOTE: This is the "WanOS Correspondent". It knows which domain maps to
# which topic, at which cadence. It receives post-drain snapshots from StateManager
# together with the set of changed domains, and routes each to the correct topic.
# The Postman (mqtt_manager) delivers the packets; this layer decides what to write.
mqtt_publisher: MqttPublisher = MqttPublisher(mqtt_client=mqtt_manager)

# 5. Bind the Z-Wave JS UI Bridge
zwave_bridge = ZWaveJSUIBridge(
    state_manager=state_manager,
    mqtt_client=mqtt_manager  # Uses the primary local WanOS broker
)
state_manager.zwave_bridge = zwave_bridge

# 6. Bind the Native RFXCOM Bridge (Dual-Use Architecture)
# Conditionally loaded to prevent crashes if the config block is omitted.
native_rfx_bridge = None
if getattr(config, "rfxcom", None) and getattr(config.rfxcom, "serial_port", None):
    try:
        from integrations.rfxcom import NativeRFXCOMBridge

        native_rfx_bridge = NativeRFXCOMBridge(
            state_manager=state_manager,
            serial_port=config.rfxcom.serial_port
        )
        # Inject into state_manager for UI telemetry tracking
        state_manager.rfxcom_bridge = native_rfx_bridge
    except Exception as e:
        logger.exception(f"CRITICAL: Crash loading NativeRFXCOMBridge: {e}")

# 7. Bind the Local Hue Bridge (API v2)
hue_bridge = None
logger.debug("DIAGNOSTIC: Checking if Hue config exists...")
if getattr(config, "hue", None) and getattr(config.hue, "bridge_ip", None):
    logger.debug(f"DIAGNOSTIC: Hue config found. IP: {config.hue.bridge_ip}. Attempting to import HueLocalBridge...")
    try:
        from integrations.hue import HueLocalBridge
        logger.debug("DIAGNOSTIC: HueLocalBridge imported successfully. Instantiating...")
        hue_bridge = HueLocalBridge(
            state_manager=state_manager,
            config=config
        )
        logger.debug("DIAGNOSTIC: HueLocalBridge instantiated successfully.")
        # Inject into state_manager for UI telemetry tracking
        state_manager.hue_bridge = hue_bridge
    except Exception as e:
        logger.debug(f"DIAGNOSTIC CRITICAL CRASH during Hue init: {e}")
        # import traceback
        # traceback.print_exc()  # Force raw Python stack trace to console
        logger.exception(f"CRITICAL: Crash loading HueLocalBridge: {e}")
else:
    logger.debug("DIAGNOSTIC: Hue config NOT found or missing bridge_ip.")

# 8. Bind the Epson Projector Bridge
epson_bridge = None
if getattr(config, "epson", None) and getattr(config.epson, "ip_address", None):
    try:
        from integrations.epson import EpsonProjector
        epson_bridge = EpsonProjector(host=config.epson.ip_address)
        state_manager.epson_bridge = epson_bridge
        logger.info(f"Epson Projector Bridge initialized at {config.epson.ip_address}")
    except Exception as e:
        logger.exception(f"CRITICAL: Crash loading EpsonProjector: {e}")

# 9. Bind the Physical Hardware Layer
hw_inputs = HardwareInputs(state_manager=state_manager)
hw_sensors = HardwareSensors(state_manager=state_manager)
hw_actuators = HardwareActuators(state_manager=state_manager)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
    """Manages startup and shutdown sequences safely without silent deadlocks."""

    logger.info("Initializing pre-boot sequence...")

    # Intercept the exact CTRL-C signal to instantly drop the SSE stream
    loop = asyncio.get_running_loop()
    try:
        for sig in (signal.SIGINT, signal.SIGTERM):
            original_handler = signal.getsignal(sig)

            def make_handler(orig=original_handler):
                def custom_handler(signum, frame):
                    def _mark():
                        state_manager._shutting_down = True
                        shutdown_event.set()
                    loop.call_soon_threadsafe(_mark)
                    if callable(orig):
                        orig(signum, frame)

                return custom_handler

            signal.signal(sig, make_handler())
    except Exception:
        pass  # Windows compatibility failsafe

    try:
        # 1. Start Network Transports
        logger.info("Connecting to local Mosquitto MQTT Broker...")
        await mqtt_manager.start()

        # 2. Initialize the state engine and wire up the publisher
        await state_manager.start()

        state_manager.mqtt_publisher = mqtt_publisher
        mqtt_publisher.start()

        # Start external bridges
        logger.debug("DIAGNOSTIC: Awaiting zwave_bridge.start()...")
        await zwave_bridge.start()
        logger.debug("DIAGNOSTIC: zwave_bridge.start() completed successfully.")
        if native_rfx_bridge:
            logger.debug("DIAGNOSTIC: Awaiting native_rfx_bridge.start()...")
            try:
                await native_rfx_bridge.start()
                logger.debug("DIAGNOSTIC: native_rfx_bridge.start() completed successfully.")
            except Exception as e:
                logger.debug(f"DIAGNOSTIC CRASH during await native_rfx_bridge.start(): {e}")
                import traceback
                traceback.print_exc()
        if hue_bridge:
            logger.debug("DIAGNOSTIC: Awaiting hue_bridge.start()...")
            try:
                await hue_bridge.start()
                logger.debug("DIAGNOSTIC: hue_bridge.start() completed successfully.")
            except Exception as e:
                logger.debug(f"DIAGNOSTIC CRASH during await hue_bridge.start(): {e}")
                import traceback
                traceback.print_exc()

        # Start Physical Hardware Layer
        logger.info("Initializing Raspberry Pi Hardware Layer...")
        await hw_inputs.start()
        await hw_sensors.start()
        await hw_actuators.start()

        # 3. Seed initial state parameters
        state_manager.dispatch(Event(type=EventType.SYSTEM_READY))
        logger.info("Core systems online. Base state ready.")

        # AUTOSTART SEQUENCE
        # Evaluates .env configuration. Spawns a non-blocking background task to wait
        # 5 seconds for local network sockets to stabilize, then fires the Master Start Sequence.
        if os.getenv("WANOS_AUTOSTART", "False").lower() == "true":
            async def delayed_autostart():
                await asyncio.sleep(5.0)
                logger.info("🚀 Executing automated Master Start Sequence (WANOS_AUTOSTART=True)...")
                # Phase 1: Arm the Brain
                state_manager.dispatch(Event(type=EventType.AUTOMATIONS_TOGGLED, payload={"enabled": True}))
                # Phase 2: Power the Actuators
                state_manager.dispatch(Event(type=EventType.HUE_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.EPSON_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.RFXCOM_TOGGLED, payload={"enabled": True}))
                # Phase 3: Enable Sonos & Onkyo
                state_manager.dispatch(Event(type=EventType.SONOS_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.ONKYO_TOGGLED, payload={"enabled": True}))
                # Phase 4: Enable Z-Wave (may defer silently until MQTT data plane is alive;
                # telemetry auto-recovery arms it when ready — no false "frozen" reject alert).
                state_manager.dispatch(Event(type=EventType.ZWAVE_TOGGLED, payload={"enabled": True}))
                # Phase 5: The OWM Cloud
                state_manager.dispatch(Event(type=EventType.OWM_TOGGLED, payload={"enabled": True}))
                # Phase 6: Arm Hardware Inputs
                state_manager.dispatch(Event(type=EventType.GPIO_INPUT_TOGGLED, payload={"enabled": True}))
                state_manager.dispatch(Event(type=EventType.SHT11_TOGGLED, payload={"enabled": True}))
                # Phase 7: Wait for stabilization (Give SHT11 loop time to parse real-world temps)
                await asyncio.sleep(2.0)
                # Phase 8: Synchronization Sweep (Outputs remain safely disarmed until UI manual intervention)
                state_manager.dispatch(Event(type=EventType.SYSTEM_SWEEP_REQUESTED, payload={}))

            asyncio.create_task(delayed_autostart())

        # 4. Start the thermodynamics engine in the background
        logger.info("Simulation engine booting...")
        physics_task = asyncio.create_task(lab_mode_thermodynamics_loop(state_manager))
        logger.info("Simulation engine initialized.")

        # 5. Start the OWM polling loop
        logger.info("[OWM] loop starting...")
        weather_task = asyncio.create_task(weather_polling_loop(state_manager))
        logger.info("[OWM] loop initialized.")

    except Exception as startup_err:
        logger.error(f"Core initialization collapsed: {startup_err}")
        os._exit(1)

    logger.success("Boot sequence complete. HTTP/SSE Web Interface online.")
    yield

    # Shutdown sequence
    logger.warning("Tearing down background engines...")
    state_manager._shutting_down = True
    shutdown_event.set()
    physics_task.cancel()
    weather_task.cancel()
    mqtt_publisher.stop()

    # Stop the physical hardware layer gracefully
    await hw_inputs.stop()
    await hw_sensors.stop()
    await hw_actuators.stop()

    if native_rfx_bridge:
        await native_rfx_bridge.stop()
    if hue_bridge:
        await hue_bridge.stop()
    await zwave_bridge.stop()

    await state_manager.stop()
    await mqtt_manager.stop()
    logger.success("Clean teardown complete. Goodbye.")

# Initialize FastAPI
app: FastAPI = FastAPI(lifespan=lifespan, title="WanOS Backend API")


# Server-Side strike tracker for brute-force protection
failed_attempts: dict[str, dict] = {}


@app.middleware("http")
async def rbac_security_middleware(request: Request, call_next):
    """Universal Pre-Flight Interceptor enforcing RBAC via Tab-Isolated JWTs."""
    path = request.url.path

    # 1. Allow open access to all static assets AND HTML pages initially.
    # The frontend JS will enforce redirection if its API calls fail.
    if path.endswith((".js", ".css", ".png", ".ico", ".svg", ".html")) and not path.startswith("/api/"):
        return await call_next(request)

    # 2. Redirect root directly to login, preserving query params (magic links)
    if path == "/":
        query_string = request.url.query
        target_url = f"/login.html?{query_string}" if query_string else "/login.html"
        return RedirectResponse(url=target_url, status_code=302)

    # 3. Allow public access to the login endpoint itself
    if path == "/api/auth/login":
        return await call_next(request)

    # 4. EXTRACT TOKEN (From Header for standard API calls, or Query string for SSE stream)
    token = None
    auth_header = request.headers.get("Authorization")
    if auth_header and auth_header.startswith("Bearer "):
        token = auth_header.split(" ")[1]
    elif request.query_params.get("jwt"):
        token = request.query_params.get("jwt")

    # 5. Verify the Token
    role = None
    if token:
        try:
            payload = jwt.decode(token, config.auth.secret_key, algorithms=["HS256"])
            role = payload.get("role")
        except Exception:
            pass

    # 6. Block unauthenticated access to the backend APIs
    if not role and path.startswith("/api/"):
        return JSONResponse(status_code=401, content={"detail": "Unauthorized. Session expired."})

    # Store role in request state so downstream endpoints can verify admin privileges
    request.state.role = role
    return await call_next(request)


class LoginRequest(BaseModel):
    pin: Optional[str] = None
    token: Optional[str] = None


@app.post("/api/auth/login")
async def login(req: LoginRequest, request: Request):
    # Use X-Forwarded-For if available to get the true client IP
    forwarded_for = request.headers.get("x-forwarded-for")
    if forwarded_for:
        client_ip = forwarded_for.split(",")[0].strip()
    else:
        client_ip = request.client.host

    now = datetime.now(timezone.utc)

    # Lazy cleanup: remove expired bans to prevent memory leaks
    expired_ips = [ip for ip, record in failed_attempts.items() if record["lockout_until"] and record["lockout_until"] < now]
    for ip in expired_ips:
        del failed_attempts[ip]

    # 1. Check IP Ban Status
    strike_record = failed_attempts.get(client_ip, {"strikes": 0, "lockout_until": None})
    if strike_record["lockout_until"] and now < strike_record["lockout_until"]:
        mins_left = int((strike_record["lockout_until"] - now).total_seconds() / 60) + 1
        return JSONResponse(status_code=429, content={"error": f"Too many attempts. Locked out for {mins_left} minutes."})

    # 2. Evaluate Credentials
    role = None
    if req.token:
        if req.token == config.auth.user_token: role = "user"
        elif req.token == config.auth.kiosk_token: role = "kiosk"
    elif req.pin:
        if req.pin == config.auth.admin_pin: role = "admin"
        elif req.pin == config.auth.user_pin or req.pin == config.auth.shared_pin: role = "user"

    # 3. Handle Failure
    if not role:
        strike_record["strikes"] += 1
        if strike_record["strikes"] >= 3:
            strike_record["lockout_until"] = now + timedelta(minutes=config.auth.ban_timeout_mins)
            strike_record["strikes"] = 0
            failed_attempts[client_ip] = strike_record
            return JSONResponse(status_code=429, content={"error": f"Too many attempts. Locked out for {config.auth.ban_timeout_mins} minutes."})

        failed_attempts[client_ip] = strike_record
        return JSONResponse(status_code=401, content={"error": "Invalid PIN."})

    # 4. Success -> Clear strikes & Issue JWT in Payload
    if client_ip in failed_attempts:
        del failed_attempts[client_ip]

    expiration = now + timedelta(days=config.auth.cookie_expiry_days)
    jwt_payload = {"role": role, "exp": expiration}
    token = jwt.encode(jwt_payload, config.auth.secret_key, algorithm="HS256")

    target_url = "/deviceexplorer.html" if role in ["admin", "user"] else "/kiosk.html"

    # Send the token directly in the JSON response body
    return JSONResponse(content={"status": "Success", "role": role, "redirect": target_url, "token": token})


@app.post("/api/auth/logout")
async def logout():
    # Cookie deletion removed. The frontend is now responsible for wiping its local tab memory.
    return JSONResponse(content={"status": "Logged out"})


class GenericEventRequest(BaseModel):
    type: Union[EventType, str]
    payload: dict[str, Any] = {}


class ZwaveConfigRequest(BaseModel):
    yaml_content: str


@app.post("/api/config/zwave")
async def update_zwave_config(request: ZwaveConfigRequest, req: Request):
    """Directly injects the YAML payload from the UI into the local server file."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    # Validate YAML content before saving
    try:
        yaml.safe_load(request.yaml_content)
    except yaml.YAMLError as e:
        logger.error(f"Invalid YAML payload received: {e}")
        return JSONResponse(status_code=400, content={"error": "Invalid YAML format."})

    try:
        file_path = os.path.join(os.path.dirname(__file__), "config_zwave.auto.yaml")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(request.yaml_content)
        return {"status": "Success", "message": "Z-Wave configuration written to disk."}
    except Exception as e:
        logger.error(f"Failed to write Z-Wave config from UI: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to save configuration file on server."})


@app.get("/api/automations")
async def list_automations(req: Request) -> dict[str, Any]:
    """Admin: list automations as schema v2 (legacy on disk is converted for the editor)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    raw = read_automations()
    out = []
    for r in raw:
        if not isinstance(r, dict):
            continue
        v2 = ordered_v2_dict(legacy_to_v2(dict(r)))
        # B10F: SR display name always = SE catalog (response + drift hide).
        _bind_sr_name_to_se_catalog(v2)
        out.append(v2)
    return {"automations": out}


@app.get("/api/automations/fire-status")
async def automations_fire_status(req: Request) -> dict[str, Any]:
    """
    B10F: today's fire status for schedule SEs + Sauna/IR OFF (admin).

    FE renders Will fire at / Has fired at / Doesn't fire today; no client schedule math.
    """
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    tm = getattr(state_manager, "_timer_manager", None)
    sauna_armed = bool(tm and tm.is_scheduled("sauna_main"))
    ir_armed = bool(tm and tm.is_scheduled("ir_main"))
    return build_automations_fire_status(
        state_manager._state,
        sauna_timer_armed=sauna_armed,
        ir_timer_armed=ir_armed,
    )


def _log_library_crud(kind: str, name: str, verb: str) -> None:
    """B10F: INFO line in wanos.log for Automations Library CRUD."""
    label = (name or "").strip() or "(unnamed)"
    logger.info(f'{kind} "{label}" {verb}')


def _rule_log_kind(rule: dict[str, Any]) -> str:
    """user rule vs system rule from primary trigger event origin."""
    eid = _primary_trigger_event_id(rule)
    if eid and eid in SYSTEM_UUID_TO_KEY:
        return "system rule"
    return "user rule"


def _primary_trigger_event_id(rule: dict[str, Any]) -> Optional[str]:
    """First event UUID on a v2 trigger (dict or list of edges)."""
    trig = rule.get("trigger")
    if isinstance(trig, dict) and trig.get("event"):
        return str(trig["event"])
    if isinstance(trig, list):
        for t in trig:
            if isinstance(t, dict) and t.get("event"):
                return str(t["event"])
    return None


def _bind_sr_name_to_se_catalog(rule: dict[str, Any]) -> None:
    """
    SR invariant: rule name always equals companion SE catalog name.

    On automations POST/PUT, if the primary trigger is a system event, overwrite
    ``name`` from the live catalog (YAML events:) or seed constant so YAML cannot
    drift (e.g. old free-text SR titles).
    """
    eid = _primary_trigger_event_id(rule)
    if not eid or eid not in SYSTEM_UUID_TO_KEY:
        return
    cat = find_event(eid)
    cat_name = ""
    if isinstance(cat, dict) and cat.get("name"):
        cat_name = str(cat["name"]).strip()
    if not cat_name:
        cat_name = str(SYSTEM_UUID_TO_NAME.get(eid) or "").strip()
    if cat_name:
        rule["name"] = cat_name


def _persist_automation_payload(rule: dict[str, Any]) -> dict[str, Any]:
    """
    Accept Y1 / flat / v2 payloads; always persist canonical v2 (Phase 6A).
    SR: force name = SE catalog name when trigger is a system event.
    """
    import uuid

    # Prefer validating known legacy shapes when not already v2
    if not is_v2_rule(rule) and (("on" in rule) or ("off" in rule)):
        parsed = BranchedAutomationRuleRequest.model_validate(rule)
        intermediate = parsed.model_dump(exclude_none=True, by_alias=True)
    elif not is_v2_rule(rule):
        parsed = FlatAutomationRuleRequest.model_validate(rule)
        intermediate = parsed.model_dump(exclude_none=True, by_alias=True)
    else:
        intermediate = rule

    v2 = ordered_v2_dict(legacy_to_v2(intermediate))
    if not v2.get("id"):
        v2["id"] = str(uuid.uuid4())
    # B10B: default enabled when missing on write.
    if "enabled" not in v2:
        v2["enabled"] = True
    # SR ↔ SE: same name (overwrite free-text / drifted YAML titles).
    _bind_sr_name_to_se_catalog(v2)
    validate_v2_entity_ids(v2)
    if not v2.get("cases"):
        raise ValueError("Automation must contain at least one case with actions.")
    for c in v2["cases"]:
        if not (c.get("actions") or []):
            raise ValueError("Each case must contain at least one action.")
    return v2


def _assert_one_system_listener(rule: dict[str, Any]) -> Optional[str]:
    """
    B10E: at most one SR may listen to a given system event (SE).
    Returns an error message or None.
    """
    eid = _primary_trigger_event_id(rule)
    if not eid or eid not in SYSTEM_UUID_TO_KEY:
        return None
    exclude = str(rule.get("id") or "") or None
    if count_system_event_listeners(eid, exclude_rule_id=exclude) >= 1:
        return (
            f"System event already has a listening rule (SR) "
            f"(one flow per system event). Event id={eid}."
        )
    return None


def _assert_u_rule_disable_allowed(rule: dict[str, Any]) -> Optional[str]:
    """
    B10E: cannot disable a user-event rule (UR) while its trigger UE is fire-referenced.
    Returns an error message or None. SR disable is always allowed here.
    """
    if rule.get("enabled", True) is not False:
        return None
    eid = _primary_trigger_event_id(rule)
    if not eid or eid in SYSTEM_UUID_TO_KEY:
        return None
    fire_refs = rule_fire_refs_to_event(eid)
    if not fire_refs:
        return None
    return (
        "Cannot disable: trigger event is fired as action by: "
        + ", ".join(fire_refs)
    )


def _automation_name_clash(name: str, exclude_id: Optional[str] = None) -> Optional[str]:
    """
    B10D: return conflicting rule id if name collides (trim + casefold), else None.
    Same-id update may keep its own name (exclude_id).
    """
    needle = normalize_event_name_key(name)  # trim + casefold helper
    if not needle:
        return "empty"
    for row in read_automations():
        if not isinstance(row, dict):
            continue
        rid = str(row.get("id") or "")
        if exclude_id and rid == exclude_id:
            continue
        if normalize_event_name_key(str(row.get("name") or "")) == needle:
            return rid or "?"
    return None


@app.post("/api/automations")
async def create_automation(rule: dict[str, Any], req: Request) -> dict[str, Any]:
    """Admin: create automation — persisted as schema v2 only."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    try:
        new_rule = _persist_automation_payload(rule)
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Invalid automation payload: {e}"})

    clash = _automation_name_clash(str(new_rule.get("name") or ""))
    if clash == "empty":
        return JSONResponse(status_code=400, content={"error": "Automation name is required."})
    if clash:
        return JSONResponse(
            status_code=409,
            content={"error": f"Automation name already in use (id={clash})."},
        )

    sys_err = _assert_one_system_listener(new_rule)
    if sys_err:
        return JSONResponse(status_code=409, content={"error": sys_err})

    disable_err = _assert_u_rule_disable_allowed(new_rule)
    if disable_err:
        return JSONResponse(status_code=409, content={"error": disable_err})

    current = read_automations()
    if any(isinstance(r, dict) and r.get("id") == new_rule["id"] for r in current if isinstance(r, dict)):
        return JSONResponse(status_code=409, content={"error": "Duplicate automation id."})

    append_automation(new_rule)
    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    _log_library_crud(_rule_log_kind(new_rule), str(new_rule.get("name") or ""), "added")
    return {"status": "Success", "automation": new_rule}


@app.put("/api/automations")
async def update_automation_api(rule: dict[str, Any], req: Request) -> dict[str, Any]:
    """Admin: replace automation by id — persisted as schema v2 only."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    try:
        dumped = _persist_automation_payload(rule)
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Invalid automation payload: {e}"})

    if not dumped.get("id"):
        return JSONResponse(status_code=400, content={"error": "PUT requires a stable automation rule `id`."})

    clash = _automation_name_clash(str(dumped.get("name") or ""), exclude_id=str(dumped["id"]))
    if clash == "empty":
        return JSONResponse(status_code=400, content={"error": "Automation name is required."})
    if clash:
        return JSONResponse(
            status_code=409,
            content={"error": f"Automation name already in use (id={clash})."},
        )

    sys_err = _assert_one_system_listener(dumped)
    if sys_err:
        return JSONResponse(status_code=409, content={"error": sys_err})

    disable_err = _assert_u_rule_disable_allowed(dumped)
    if disable_err:
        return JSONResponse(status_code=409, content={"error": disable_err})

    if not update_automation(dumped["id"], dumped):
        return JSONResponse(status_code=404, content={"error": f"Automation id '{dumped['id']}' not found."})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    _log_library_crud(_rule_log_kind(dumped), str(dumped.get("name") or ""), "changed")
    return {"status": "Success", "automation": dumped}


@app.delete("/api/automations")
async def delete_automation_api(req_body: AutomationsRuleIdRequest, req: Request) -> dict[str, Any]:
    """Admin: delete an automation rule by id from automations.auto.yaml."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    # Snapshot name/kind for B10F CRUD INFO before remove.
    prior: Optional[dict[str, Any]] = None
    for row in read_automations():
        if isinstance(row, dict) and str(row.get("id") or "") == str(req_body.id):
            prior = row
            break

    if not delete_automation(req_body.id):
        return JSONResponse(status_code=404, content={"error": f"Automation id '{req_body.id}' not found."})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    if prior:
        try:
            v2 = ordered_v2_dict(legacy_to_v2(dict(prior)))
            _log_library_crud(_rule_log_kind(v2), str(v2.get("name") or prior.get("name") or ""), "deleted")
        except Exception:
            _log_library_crud("user rule", str(prior.get("name") or req_body.id), "deleted")
    return {"status": "Success"}


class EventsIdRequest(BaseModel):
    """DELETE /api/events body — mirror AutomationsRuleIdRequest."""
    id: str


@app.get("/api/events")
async def list_events_api(req: Request) -> dict[str, Any]:
    """Admin: list events: catalog rows (ensure Y1 system seeds merged first)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    try:
        merge_system_seeds_into_yaml()
    except FileNotFoundError:
        pass
    except Exception as e:
        return JSONResponse(status_code=500, content={"error": f"Failed to merge system event seeds: {e}"})
    return {"events": read_events()}


@app.post("/api/events")
async def create_event_api(body: dict[str, Any], req: Request) -> dict[str, Any]:
    """Admin: create a user event row (server assigns UUID)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    try:
        row = create_user_event(
            str(body.get("name") or ""),
            show_on_dashboard=bool(body.get("show_on_dashboard", False)),
            require_confirmation=bool(body.get("require_confirmation", False)),
            enabled=bool(body.get("enabled", True)),
        )
    except ValueError as e:
        msg = str(e)
        code = 409 if "already in use" in msg or "Duplicate event id" in msg else 400
        return JSONResponse(status_code=code, content={"error": msg})
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Invalid event payload: {e}"})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    _log_library_crud("user event", str(row.get("name") or ""), "added")
    return {"status": "Success", "event": row}


@app.put("/api/events")
async def update_event_api(body: dict[str, Any], req: Request) -> dict[str, Any]:
    """Admin: replace event by id (B10E: system dashboard rejected; confirm coerced)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    try:
        row = update_event(body)
    except KeyError as e:
        return JSONResponse(status_code=404, content={"error": str(e)})
    except ValueError as e:
        msg = str(e)
        code = 409 if "already in use" in msg or "Cannot disable" in msg else 400
        return JSONResponse(status_code=code, content={"error": msg})
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": f"Invalid event payload: {e}"})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    # System events are largely immutable; still log when a write succeeds.
    kind = "system event" if str(row.get("id") or "") in SYSTEM_UUID_TO_KEY else "user event"
    _log_library_crud(kind, str(row.get("name") or ""), "changed")
    return {"status": "Success", "event": row}


@app.get("/api/events/{event_id}/usages")
async def event_usages_api(event_id: str, req: Request) -> dict[str, Any]:
    """
    Admin: Show usages — rules that listen (trigger) OR fire this event.
    Both sides block user-event disable; UI lists the union of names.
    """
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    listened_by = rule_trigger_refs_to_event(event_id)
    fired_by = rule_fire_refs_to_event(event_id)
    # Stable unique union (listeners first, then fire-only names).
    seen: set[str] = set()
    used_by: list[str] = []
    for nm in listened_by + fired_by:
        if nm not in seen:
            seen.add(nm)
            used_by.append(nm)
    return {
        "event_id": event_id,
        "listened_by": listened_by,
        "fired_by": fired_by,
        "used_by": used_by,
    }


@app.delete("/api/events")
async def delete_event_api(req_body: EventsIdRequest, req: Request) -> dict[str, Any]:
    """Admin: delete a user event by id (guards → 409)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    prior = find_event(req_body.id)
    prior_name = ""
    if isinstance(prior, dict):
        prior_name = str(prior.get("name") or "")
    try:
        delete_event(req_body.id)
    except KeyError as e:
        return JSONResponse(status_code=404, content={"error": str(e)})
    except ValueError as e:
        return JSONResponse(status_code=409, content={"error": str(e)})
    except Exception as e:
        return JSONResponse(status_code=400, content={"error": str(e)})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    _log_library_crud("user event", prior_name or str(req_body.id), "deleted")
    return {"status": "Success"}


class SoftHidePutRequest(BaseModel):
    entity_ids: list[str]


@app.get("/api/soft-hide")
async def get_soft_hide(req: Request) -> dict[str, Any]:
    """Admin: list soft-hidden entity_ids (deviceexplorer_hide)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    return {"entity_ids": read_soft_hide_entity_ids()}


@app.put("/api/soft-hide")
async def put_soft_hide(body: SoftHidePutRequest, req: Request) -> dict[str, Any]:
    """Admin: replace soft-hide list; surgical write + hot-reload."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    # Validate known eids against live registry when available
    unknown: list[str] = []
    denied: list[str] = []
    for raw in body.entity_ids:
        eid = str(raw).strip()
        if not eid:
            continue
        if is_hard_deny_entity_id(eid):
            denied.append(eid)
            continue
        if state_manager.resolve_entity_id(eid) is None:
            unknown.append(eid)
    if denied:
        return JSONResponse(
            status_code=400,
            content={"error": f"Hard-deny entity_ids not allowed: {', '.join(denied)}"},
        )
    if unknown:
        return JSONResponse(
            status_code=400,
            content={"error": f"Unknown entity_ids: {', '.join(unknown)}"},
        )

    try:
        written = write_soft_hide_entity_ids(body.entity_ids)
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})
    except Exception as e:
        logger.error(f"soft-hide write failed: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to write soft-hide list."})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    return {"status": "Success", "entity_ids": written}


class AutoOffPutRequest(BaseModel):
    managed_auto_off: list[str] = []
    default_auto_off_minutes: int = 300
    default_pertype_auto_off_minutes: dict[str, int] = {}
    auto_off_delays: dict[str, int] = {}


def _live_type_for_eid(eid: str) -> Optional[str]:
    idx = state_manager.resolve_entity_id(eid)
    if idx is None:
        return None
    meta = state_manager.get_state_snapshot().device_metadata.get(idx) or {}
    if isinstance(meta, dict) and meta.get("type"):
        return str(meta.get("type"))
    return None


@app.get("/api/auto-off-timer")
async def get_auto_off_timer(req: Request) -> dict[str, Any]:
    """Admin: read auto_off_devices block."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    return read_auto_off_config()


@app.put("/api/auto-off-timer")
async def put_auto_off_timer(body: AutoOffPutRequest, req: Request) -> dict[str, Any]:
    """Admin: full-replace auto_off_devices; surgical write + hot-reload."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    try:
        managed = sanitize_managed_list(body.managed_auto_off)
        general = normalize_minutes(body.default_auto_off_minutes)
        pertype = sanitize_pertype_map(body.default_pertype_auto_off_minutes)
        delays = sanitize_delay_map(body.auto_off_delays)
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})

    managed_set = set(managed)
    unknown: list[str] = []
    ineligible: list[str] = []
    for eid in managed:
        if state_manager.resolve_entity_id(eid) is None:
            unknown.append(eid)
            continue
        dtype = _live_type_for_eid(eid)
        if not is_auto_off_eligible(eid, dtype):
            ineligible.append(eid)
    for eid in delays:
        if eid not in managed_set:
            return JSONResponse(
                status_code=400,
                content={"error": f"auto_off_delays orphan '{eid}' (must be in managed_auto_off)"},
            )
        if state_manager.resolve_entity_id(eid) is None and eid not in unknown:
            unknown.append(eid)
    bad_types = [t for t in pertype if t not in AUTO_OFF_ALLOWED_TYPES]
    if bad_types:
        return JSONResponse(
            status_code=400,
            content={"error": f"Invalid type keys: {', '.join(bad_types)}"},
        )
    if unknown:
        return JSONResponse(
            status_code=400,
            content={"error": f"Unknown entity_ids: {', '.join(unknown)}"},
        )
    if ineligible:
        return JSONResponse(
            status_code=400,
            content={"error": f"Ineligible entity_ids: {', '.join(ineligible)}"},
        )

    try:
        written = write_auto_off_config(
            managed_auto_off=managed,
            default_auto_off_minutes=general,
            default_pertype_auto_off_minutes=pertype,
            auto_off_delays=delays,
        )
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})
    except Exception as e:
        logger.error(f"auto-off-timer write failed: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to write auto-off config."})

    state_manager.dispatch(Event(type=EventType.CONFIG_RELOAD_REQUESTED, payload={"source": "api"}))
    return {"status": "Success", **written}


@app.get("/api/state")
async def get_state() -> dict[str, Any]:
    return state_manager.get_state_snapshot().model_dump()


@app.get("/api/debug/entity-registry-check")
async def debug_entity_registry_check(req: Request) -> dict[str, Any]:
    """Admin Debug: entity_id / automation consistency checks (keep after cutover)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    from core.entity_registry_check import run_entity_cutover_checks

    report = run_entity_cutover_checks(
        device_metadata=state_manager.get_state_snapshot().device_metadata,
    )
    return report


@app.get("/api/admin/entity-id-list")
async def admin_entity_id_list(req: Request):
    """Admin: download live entity_id authoring list (core.entity_id_list)."""
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})
    from core.entity_id_list import generate_entity_id_list_text

    try:
        text = generate_entity_id_list_text()
    except FileNotFoundError as e:
        return JSONResponse(status_code=404, content={"error": str(e)})
    except Exception as e:
        logger.error(f"Failed to generate entity_id list: {e}")
        return JSONResponse(status_code=500, content={"error": "Failed to generate entity_id list."})

    return Response(
        content=text,
        media_type="text/plain; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="entity_id-list.txt"'},
    )


@app.post("/api/admin/restart")
async def admin_restart_wanos(req: Request) -> JSONResponse:
    """Admin: restart WanOS systemd unit (service only — not the host).

    Requires passwordless sudo for:
      /usr/bin/systemctl restart wanos.service
    Returns 202 when the restart command is accepted; UI reconnects after the unit is back.
    """
    if req.state.role != "admin":
        return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    cmd = ["sudo", "-n", "/usr/bin/systemctl", "restart", "wanos.service"]
    try:
        # Fire-and-forget-ish: accept quickly; systemd will kill this process during restart.
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        # Brief wait so we can surface sudo/NOPASSWD failures before the unit dies.
        try:
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=3.0)
        except asyncio.TimeoutError:
            # Restart likely accepted and this process is being stopped — treat as success.
            logger.info("admin restart: systemctl still running after 3s (likely restarting)")
            return JSONResponse(status_code=202, content={"ok": True, "message": "Restart accepted"})

        if proc.returncode != 0:
            err = (stderr or b"").decode("utf-8", errors="replace").strip()
            out = (stdout or b"").decode("utf-8", errors="replace").strip()
            detail = err or out or f"systemctl exit {proc.returncode}"
            logger.error(f"admin restart failed: {detail}")
            return JSONResponse(
                status_code=500,
                content={
                    "error": (
                        "Failed to restart WanOS service. "
                        "Check passwordless sudo for "
                        "'systemctl restart wanos.service'. "
                        f"Detail: {detail}"
                    )
                },
            )
        logger.info("admin restart: systemctl restart wanos.service accepted")
        return JSONResponse(status_code=202, content={"ok": True, "message": "Restart accepted"})
    except Exception as e:
        logger.error(f"admin restart exception: {e}")
        return JSONResponse(status_code=500, content={"error": f"Restart failed: {e}"})


def _require_history_reader(req: Request):
    """Device/session history is available to admin and user roles."""
    if req.state.role not in ("admin", "user"):
        return JSONResponse(status_code=403, content={"error": "Forbidden: Login required."})
    return None


@app.get("/api/history/sensors")
async def history_sensors(req: Request):
    denied = _require_history_reader(req)
    if denied:
        return denied
    return {"sensors": state_manager.sensor_history.list_sensors()}


@app.get("/api/history/actuators")
async def history_actuators(req: Request):
    denied = _require_history_reader(req)
    if denied:
        return denied
    return {"actuators": state_manager.history_manager.list_actuators()}


@app.get("/api/history/actuators/{idx}")
async def history_actuator_series(idx: int, req: Request, range: str = "day"):
    denied = _require_history_reader(req)
    if denied:
        return denied
    range_name = range if range in ("day", "month", "year") else "day"
    return state_manager.history_manager.get_actuator_series(idx, range_name)


@app.get("/api/history/sessions")
async def history_sessions(
    req: Request,
    type: str = "sauna",
    limit: int = 50,
    offset: int = 0,
):
    denied = _require_history_reader(req)
    if denied:
        return denied
    session_type = type if type in ("sauna", "ir") else "sauna"
    limit = max(1, min(limit, 200))
    offset = max(0, offset)
    return state_manager.sensor_history.get_sessions(session_type, limit=limit, offset=offset)


@app.get("/api/history/{idx}/summary")
async def history_summary(idx: int, req: Request):
    denied = _require_history_reader(req)
    if denied:
        return denied
    return state_manager.sensor_history.get_summary(idx)


@app.get("/api/history/{idx}")
async def history_series(idx: int, req: Request, range: str = "day"):
    denied = _require_history_reader(req)
    if denied:
        return denied
    range_name = range if range in ("day", "month", "year") else "day"
    return state_manager.sensor_history.get_series(idx, range_name)


@app.post("/api/event")
async def inject_event(request: GenericEventRequest, req: Request) -> dict[str, Union[str, Event]]:
    e_type_str = request.type.value if hasattr(request.type, 'value') else str(request.type)
    # Normalize catalog keys → UUID before admin checks / dispatch.
    bus_token = to_bus_token(e_type_str)

    # Block users/kiosks from performing system-level administration toggles
    admin_only_events = ["CONFIG_RELOAD_REQUESTED", "SYSTEM_SWEEP_REQUESTED", "SIMULATIONS_TOGGLED"]
    if req.state.role != "admin":
        if e_type_str in admin_only_events or e_type_str.endswith("_TOGGLED"):
            return JSONResponse(status_code=403, content={"error": "Forbidden: Admin privileges required."})

    try:
        e_type: Any = EventType(bus_token)
    except ValueError:
        e_type = bus_token

    event: Event = Event(type=e_type, payload=request.payload)
    state_manager.dispatch(event)
    return {"status": "Event dispatched", "event": event}


@app.get("/api/state/sse")
async def sse_state_stream(request: Request):
    """
    Delta SSE stream. Emits only changed domain subtrees after each event queue drain.
    Payload format: {"domain": "<key>", "data": { ... }}
    The frontend fetches /api/state on connect for the full snapshot, then
    applies these partial updates by domain key as they arrive.
    """

    async def event_generator():
        # Track the last emitted snapshot per domain to suppress redundant pushes
        last_domain_snapshots: dict[str, str] = {}
        import time
        last_ping_time = time.time()

        try:
            while not shutdown_event.is_set():
                if await request.is_disconnected():
                    break

                current_state = state_manager.get_state_snapshot()
                data_sent = False

                # Emit only domains whose serialized content has changed since last push
                for domain in ["system", "sensors", "sauna", "ir", "metrics", "hardware", "devices", "device_metadata"]:
                    domain_data = getattr(current_state, domain, None)
                    if domain_data is None:
                        continue

                    # Serialize the domain subtree for diffing
                    if hasattr(domain_data, "model_dump"):
                        domain_json = json.dumps(domain_data.model_dump())
                    else:
                        domain_json = json.dumps(domain_data)

                    if last_domain_snapshots.get(domain) != domain_json:
                        # This is where the data is sent to the frontend, app.js
                        payload = json.dumps({"domain": domain, "data": json.loads(domain_json)})
                        yield f"data: {payload}\n\n"
                        last_domain_snapshots[domain] = domain_json
                        data_sent = True

                # 💓 INTUITIVE APP-LEVEL HEARTBEAT MONITOR
                now = time.time()
                if data_sent:
                    # If live structural state updates went out, they double as our keep-alive
                    last_ping_time = now
                elif now - last_ping_time >= 5.0:
                    # Pipe an explicit, silent data block if the channel remains quiet for 5 seconds
                    ping_payload = json.dumps({"domain": "ping", "data": {}})
                    yield f"data: {ping_payload}\n\n"
                    last_ping_time = now

                await asyncio.sleep(0.5)
        except asyncio.CancelledError:
            pass

    return StreamingResponse(event_generator(), media_type="text/event-stream")


# TIER 3 CACHE-BUSTING MIDDLEWARE
# Intercepts every outgoing HTTP request. If the browser is asking for a frontend asset
# (HTML, JS, CSS), we forcefully inject HTTP headers forbidding the browser from caching it.
@app.middleware("http")
async def add_no_cache_headers(request: Request, call_next):
    response = await call_next(request)

    # Do not mess with API endpoints or SSE streams, only static files.
    if not request.url.path.startswith("/api/"):
        response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "0"
    return response


frontend_path = os.path.join(os.path.dirname(__file__), "frontend")
if os.path.exists(frontend_path):
    app.mount("/", StaticFiles(directory=frontend_path, html=True), name="frontend")
else:
    logger.warning(f"⚠️ Warning: Frontend directory not found at {frontend_path}")