#!/usr/bin/env bash
# --- file: .cursor/install.sh ---
# Cloud Agent install phase for WanOS (idempotent).
#
# Prepares a portable, hardware-free "lab mode" development environment:
#   - system packages (Mosquitto broker + build tooling)
#   - Python venv with the non-Raspberry-Pi subset of requirements.txt
#   - a dev .env (generated once; gitignored) with a local MQTT secret
#   - the SQLite analytics DB, initialized with the app's own schema
#   - the /var/log/wanos log directory the backend writes to on the Pi
#
# Site-specific hardware (lgpio / RPi.GPIO / SHT11 / RFXCOM serial) is absent
# in the cloud VM; the backend already degrades those layers to stub mode, and
# the bundled thermodynamics simulator ("Lab Mode") provides live sensor data.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

VENV_DIR="$REPO_ROOT/.venv"
REQ_SRC="$REPO_ROOT/requirements.txt"
REQ_DEV="$REPO_ROOT/.cursor/runtime/requirements-dev.txt"

echo "[install] repo root: $REPO_ROOT"

# 1. System packages (broker, build tools, venv support).
echo "[install] installing system packages..."
sudo apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    mosquitto mosquitto-clients python3-venv python3-dev build-essential

# The Debian package auto-starts a system broker; we run our own authenticated
# broker from start.sh, so stop and disable the default unit (best effort).
sudo systemctl stop mosquitto 2>/dev/null || true
sudo systemctl disable mosquitto 2>/dev/null || true

# 2. Log directory the backend logger writes to (matches the Pi deployment).
echo "[install] ensuring /var/log/wanos ..."
sudo mkdir -p /var/log/wanos
sudo chown "$(id -u):$(id -g)" /var/log/wanos

# 3. Python virtual environment.
if [ ! -x "$VENV_DIR/bin/python" ]; then
    echo "[install] creating venv at $VENV_DIR ..."
    python3 -m venv "$VENV_DIR"
fi
# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"
python -m pip install --upgrade pip setuptools wheel

# 4. Derive a hardware-free requirements file from the canonical requirements.txt.
#    requirements.txt stays the single source of truth for versions; we only drop
#    packages that cannot run off a Raspberry Pi (and the lgpio source-build flag).
mkdir -p "$REPO_ROOT/.cursor/runtime"
grep -viE '^[[:space:]]*(--no-binary[[:space:]]+lgpio|lgpio==|RPi\.GPIO==|pi-sht1x==)' \
    "$REQ_SRC" > "$REQ_DEV"
echo "[install] installing Python requirements (hardware-free subset)..."
pip install -r "$REQ_DEV"

# 5. Dev .env (generated once; gitignored). Holds only local/dev secrets.
if [ ! -f "$REPO_ROOT/.env" ]; then
    echo "[install] generating dev .env ..."
    cat > "$REPO_ROOT/.env" <<EOF
# --- file: .env (dev, generated by .cursor/install.sh; gitignored) ---
# Local-only development secrets. Do not reuse in production.
WANOS_MQTT_PASSWORD=wanos_dev_$(openssl rand -hex 8)
OWM_API_KEY=""
HUE_API_KEY=""
USER_PIN=1111
ADMIN_PIN=1234
SECRET_KEY="$(openssl rand -hex 32)"
WANOS_AUTOSTART=False
EOF
else
    echo "[install] .env already present; leaving it untouched."
fi

# 6. Initialize the SQLite analytics DB using the application's own schema.
#    On the Pi this file already exists; on a fresh VM the first-boot code path
#    assumes the session tables exist, so we create them here via the app itself.
echo "[install] initializing sauna_sessions.db ..."
python - <<'PY'
from logic.power_analytics import PowerAnalytics
from logic.sauna_session_telemetry import SaunaSessionTelemetry

pa = PowerAnalytics.__new__(PowerAnalytics)
pa._db_path = "sauna_sessions.db"
pa.sm = None
pa.session_telemetry = SaunaSessionTelemetry(pa)
pa._init_sqlite()
print("[install] DB schema ready.")
PY

echo "[install] done."
