[global]
   workgroup = WORKGROUP
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d
   
   # Disable printer sharing subsystems to optimize speed
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

[wanos_share]
   path = /home/wannes/wisc_backend
   writeable = yes
   create mask = 0775
   directory mask = 0775
   public = no
   valid users = wannes